Proofreading fixes part 2 - Android basic security testing
OWASP/owasp-mastg pull request #2297
Opened 2022-10-24 03:24 UTC by Laancelot

Links, typos

Thank you for submitting a Pull Request to the OWASP MASTG. Please make sure that:

- [ ] Your contribution is written in the 2nd person (e.g. you)
- [ ] Your contribution is written in an active present form for as much as possible.
- [ ] You have made sure that the reference section is up to date (e.g. please add sources you have used, make sure that the references to MITRE/MASVS/etc. are up to date)
- [ ] Your contribution has proper formatted markdown and/or code
- [ ] Any references to website have been formatted as [TEXT](URL “NAME”)
- [ ] You verified/tested the effectiveness of your contribution (e.g.: is the code really an effective remediation? Please verify it works!)

If your PR is related to an issue. Please end your PR test with the following line:
This PR closes #< insert number here >.

2022-10-24 03:33 UTC, Laancelot commented
the URL checker failed on the URL that was changed in a previous pull request (Android basic security testing part 1) that hasn't been merged yet

2022-10-25 08:38 UTC, Faby666 reviewed
#2297

2022-10-25 10:53 UTC, cpholguera requested changes
Hi @Laancelot, thanks for adding missing links.

I got just one comment to that. 

Instead of:

```suggestion
 "[Recommended Tools - Objection](https://github.com/OWASP/owasp-mastg/blob/master/Document/0x08a-Testing-Tools.md#objection "Testing Tools - Objection")"
```

It should be:

```suggestion
 "[Recommended Tools - Objection](0x08a-Testing-Tools.md#objection "Testing Tools - Objection")"
```

Could you please correct them? Thank you very much!

2022-10-25 23:54 UTC, Laancelot commented
done @cpholguera

2022-10-26 06:15 UTC, cpholguera commented
I'm sorry @Laancelot but the GitHub rendering for the markdown block above was broken and it was showing a link instead of a block of code. Please take another look because the links are different. Thank you very much again!

2022-10-26 06:21 UTC, cpholguera requested changes
Sending the right links as suggestions, thanks @Laancelot!

2022-10-26 06:21 UTC, cpholguera commented on Document/0x05b-Basic-Security_Testing.md
> +First, connect to the app with Objection as explained in "[Recommended Tools - Objection](https://github.com/OWASP/owasp-mastg/pull/0x08a-Testing-Tools.md#objection "Testing Tools - Objection")". The
Thanks for adding missing links

```suggestion
First, connect to the app with Objection as explained in "[Recommended Tools - Objection](0x08a-Testing-Tools.md#objection "Testing Tools - Objection")". Then, use `ls` and `cd` as you normally would on your terminal to explore the available files:
```

2022-10-26 06:21 UTC, cpholguera commented on Document/0x05b-Basic-Security_Testing.md
> +Refer to the "[Testing Data Storage](https://github.com/OWASP/owasp-mastg/pull/0x05d-Testing-Data-Storage.md "Testing Data Storage")" chapter for more information and best practices on securely stori
```suggestion
Refer to the "[Testing Data Storage](0x05d-Testing-Data-Storage.md "Testing Data Storage")" chapter for more information and best practices on securely storing sensitive data.
```

2022-10-26 06:21 UTC, cpholguera commented on Document/0x05b-Basic-Security_Testing.md
> +- Debuggable flag: `debuggable` (see "[Code Quality and Build Settings of Android Apps](https://github.com/OWASP/owasp-mastg/pull/0x05i-Testing-Code-Quality-and-Build-Settings.md "Testing Code Qualit
```suggestion
- App permissions: `permission` (see "[Android Platform APIs](https://github.com/OWASP/owasp-mastg/pull/0x05h-Testing-Platform-Interaction.md "Testing Platform Interaction")")
- Backup allowance: `android:allowBackup` (see "[Data Storage on Android](0x05d-Testing-Data-Storage.md "Testing Data Storage)")
- App components: `activity`, `service`, `provider`, `receiver` (see "[Android Platform APIs](0x05h-Testing-Platform-Interaction.md "Testing Platform Interaction")" and "[Data Storage on Android](0x05d-Testing-Data-Storage.md "Testing Data Storage)")
- Debuggable flag: `debuggable` (see "[Code Quality and Build Settings of Android Apps](0x05i-Testing-Code-Quality-and-Build-Settings.md "Testing Code Quality and Build Settings")")
```

2022-10-27 10:19 UTC, cpholguera approved these changes
Thanks @Laancelot!

2022-10-27 10:19 UTC, cpholguera commented on Document/0x05b-Basic-Security_Testing.md
> +- App permissions: `permission` (see "[Android Platform APIs](https://github.com/OWASP/owasp-mastg/pull/0x05h-Testing-Platform-Interaction.md "Testing Platform Interaction")")
```suggestion
- App permissions: `permission` (see "[Android Platform APIs](0x05h-Testing-Platform-Interaction.md "Testing Platform Interaction")")
```

2022-10-27 10:22 UTC, merged