Add steps for Frida snippet generation from JADX
OWASP/owasp-mastg pull request #2331
Opened 2022-12-03 21:26 UTC by cgarst

Detailing a feature added in JADX 1.3.3 where basic Frida scripts to capture method entry/exit parameters can be dynamically generated through the decompiler's graphical code browser.

--------------

Thank you for submitting a Pull Request to the OWASP MASTG. Please make sure that:

- [✓] Your contribution is written in the 2nd person (e.g. you)
- [✓] Your contribution is written in an active present form for as much as possible.
- [✓] You have made sure that the reference section is up to date (e.g. please add sources you have used, make sure that the references to MITRE/MASVS/etc. are up to date)
- [✓] Your contribution has proper formatted markdown and/or code
- [✓] Any references to website have been formatted as [TEXT](URL “NAME”)
- [✓] You verified/tested the effectiveness of your contribution (e.g.: is the code really an effective remediation? Please verify it works!)

This PR closes #2070

2022-12-04 18:46 UTC, cpholguera requested changes
Just a couple of corrections and we're ready to go. Thank you @cgarst!

2022-12-04 18:46 UTC, cpholguera commented on Document/0x08a-Testing-Tools.md
> +The [JADX decompiler](https://github.com/skylot/jadx) can generate Frida snippets through it's graphical code browser which print method entry and exit parameters via a `Java.use` call. To use this f
```suggestion
The [JADX decompiler](#jadx) (v1.3.3 and above) can generate Frida snippets through its graphical code browser. To use this feature, open the APK or DEX with `jadx-gui`, browse to the target method, right click the method name, and select "Copy as frida snippet (f)". For example using the MASTG [UnCrackable App for Android Level 1](0x08b-Reference-Apps.md#android-uncrackable-l1):
```

2022-12-04 18:46 UTC, cpholguera commented on Document/0x08a-Testing-Tools.md
> +The above steps place the following output in pasteboard to be pasted in a `.js` file and fed into `frida -U -l`.
```suggestion
The above steps place the following output in the pasteboard, which you can then paste in a JavaScript file and feed into `frida -U -l`.
```

2022-12-04 18:46 UTC, cpholguera commented on Document/0x08a-Testing-Tools.md
> +```java
```suggestion
```javascript
```

2022-12-04 18:46 UTC, cpholguera commented on Document/0x08a-Testing-Tools.md
> +The above code generated by `jadx-gui` hooks the `a` method within the `sg.vantagepoint.a.a` class and logs it's entry parameters and return values.
```suggestion
The above code hooks the `a` method within the `sg.vantagepoint.a.a` class and logs its input parameters and return values.
```

2022-12-05 01:37 UTC, cgarst commented
Fixed, thanks!

2022-12-05 11:38 UTC, cpholguera approved these changes
Thanks a lot @cgarst!

2022-12-05 11:38 UTC, merged