Proofreading fix on MASTG-TEST-0085.md -> Checking for Weaknesses in Third Party Libraries ( by @appknox )
OWASP/owasp-mastg pull request #2554
Opened 2024-02-14 12:39 UTC by sk3l10x1ng

The code block under "Listing Application Libraries"  is not closed properly. 
As a result, the entire section of  "Make Sure That Free Security Features Are Activated" topic is included inside a code block on page no. 505 of MASTG pdf release v1.7.0

2024-02-14 14:31 UTC, cpholguera requested changes

2024-02-14 14:31 UTC, cpholguera commented on tests/ios/MASVS-CODE/MASTG-TEST-0085.md
> +```
Please go back to v1.5.0 and get the missing text from the original test in 
 Document/0x06i-Testing-Code-Quality-and-Build-Settings.md

2024-02-20 10:29 UTC, sushi2k approved these changes

2024-02-20 10:35 UTC, cpholguera approved these changes

2024-02-20 10:35 UTC, merged