Add Risk and Test - Weak Cryptographic Key Generation [weak-crypto-key-generation] (by appknox)
OWASP/owasp-mastg pull request #2622
Opened 2024-05-22 03:08 UTC by sk3l10x1ng

#2573 closes

2024-06-22 05:04 UTC, sushi2k requested changes
Thanks you @sk3l10x1ng for the PR! Have a look at the comments. The main change that is needed is to not mention AES-128 as insecure algorithm. You could use AES-64 instead as example. Let me know if any questions

2024-06-22 05:04 UTC, sushi2k commented on risks/MASVS-CRYPTO/2-weak-crypto-key-generation/weak-key-generation/android-weak-key-generation/rules/mastg-weak-crypto-key-generation.yml
> +rules:
Let's add the source, if it wasn't done by us from scratch.

```suggestion
# original source: https://github.com/MobSF/mobsfscan/blob/main/mobsfscan/rules/semgrep/crypto/weak_key_size.yaml
rules:
```

2024-06-22 05:04 UTC, sushi2k commented on risks/MASVS-CRYPTO/2-weak-crypto-key-generation/weak-key-generation/android-weak-key-generation/demo-1/output.sarif
> +{
Can you please remove the SARIF file for now? We can add later to keep the PR cleaner.

2024-07-04 12:26 UTC, sk3l10x1ng commented
> Thanks you @sk3l10x1ng for the PR! Have a look at the comments. The main change that is needed is to not mention AES-128 as insecure algorithm. You could use AES-64 instead as example. Let me know if any questions

@sushi2k 
- We have created the test case on AES-128 bit based on the following examples  provided in the issue #2573 . 
- Can we use DES algorithm for the test case for the ios . Where AES-64 is not possible because the contain key sizes 128, 192, 256

2024-07-28 05:32 UTC, sushi2k commented
Hi @sk3l10x1ng. You could use 3DES, as this is algorithm is deprecated, instead of AES-128. You are right AES-128 is listed as example in the issue, but this is not correct.
Can you please also go through my comments and follow-up on them? Regarding the test cases and weaknesses we have a new structure which can be found here: <https://docs.google.com/document/d/1EMsVdfrDBAu0gmjWAUEs60q-fWaOmDB5oecY9d9pOlg/edit?usp=sharing>. Can you please update the content to this new format?  Let me know if any questions. 

Thanks for your support.

2024-07-30 11:39 UTC, sk3l10x1ng commented
@cpholguera @sushi2k . updated according to new file structure in #2849

2024-07-30 11:39 UTC, closed without merging