[MASWE-0020] Weak Encryption (by @appknox)
OWASP/owasp-mastg pull request #2910
Opened 2024-10-10 12:29 UTC by sk3l10x1ng

#2584 closes

2024-10-18 04:27 UTC, sushi2k requested changes
Finished the weakness part. I applied my suggestions, let me know if anything to change from your end. Please look into the meta data of the weakness and clean it up accordingly.

Will look into the other parts in the upcoming days. Thanks for your contribution!

2024-10-18 04:27 UTC, sushi2k commented on weaknesses/MASVS-CRYPTO/MASWE-0020.md
> +Weak encryption denotes cryptographic systems or implementations that exhibit vulnerabilities to attacks, allowing unauthorized individuals to decrypt secured data with minimal effort. This inadequac
Let's focus on AES and ECB that shouldn't be used, which is also highlighted in the android and other documentations instead of DES.

```suggestion
Weak encryption refers to cryptographic systems or implementations that are vulnerable to attack, allowing unauthorised individuals to decrypt secured data. This weakness can be due to a number of reasons, including the use of outdated algorithms, deprecated encryption modes such as ECB and improper implementation practices such as the use of a non-random or empty Initialisation Vector (IV). 

For example the use of TDEA (Triple Data Encryption Algorithm), which is often referred to as "Triple DES" or "3DES" is disallowed by NIST since end of 2023, due to known attacks like, "meet-in-the-middle", collision attacks and [Sweet32](https://nvd.nist.gov/vuln/detail/CVE-2016-2183).

Similarly, hash functions such as MD5 and SHA-1, which were previously popular for ensuring data integrity, are now considered deprecated as attackers can generate hash collisions, potentially leading to data tampering.
```

2024-10-18 04:27 UTC, sushi2k commented on weaknesses/MASVS-CRYPTO/MASWE-0020.md
> +- **Loss of  Confidentiality**: Weak encryption may enable attackers to decipher and obtain sensitive information, resulting in unauthorized exposure and possible data breaches.
```suggestion
- **Loss of Confidentiality**: Weak encryption may enable attackers to decipher and obtain sensitive information, resulting in unauthorized exposure and possible data breaches.
```

2024-10-18 04:27 UTC, sushi2k commented on weaknesses/MASVS-CRYPTO/MASWE-0020.md
> +- **Loss of Integrity**: Weak encryption may compromise the integrity of data, allowing adversaries to exploit vulnerabilities and potentially alter or manipulate the information without detection.
```suggestion
- **Loss of Integrity**: Weak encryption can compromise the integrity of data, allowing adversaries to alter or manipulate the information without detection.
```

2024-10-18 04:27 UTC, sushi2k commented on weaknesses/MASVS-CRYPTO/MASWE-0020.md
> +- **Use of Deprecated Algorithms** : Relying on outdated or weak cryptographic algorithms can produce keys that are less secure. Such algorithms are often characterized by vulnerabilities or the abil
Let's make this more granular: 

```suggestion
- **Use of Deprecated Algorithms** : Relying on outdated or weak cryptographic algorithms can allow threat actors to attack the cipher text, key or exploit known vulnerabilities in the algorithm, for example through brute force attacks.
- **Insecure Modes of Operation**:  Using modes that are considered deprecated increase the attack surface of encrypted information. For example the use of AES/ECB is deprecated as it divides the plaintext into blocks and encrypts each block separately using the same key. This makes the cipher text vulnerable to "known plaintext attacks" and leaks information about the structure of the original plaintext. 
- **Predictable Initialization Vectors (IVs)**: If IVs are not random or unique, they can be exploited in attacks like ciphertext injection or pattern recognition. This compromises the confidentiality of encrypted data, especially in modes like CBC (Cipher Block Chaining).
- **Weak Keys**: Short or easily guessable keys compromise encryption strength. The use of small key sizes (e.g., 56-bit keys in DES) can make the encryption susceptible to brute-force attacks. Best practices recommend keys of at least 256 bits for strong encryption.
- **Misuse of Non-Cryptographic Operations**: Relying on techniques such as XOR, Base64 encoding, or simple obfuscation methods for security purposes. These methods provide no actual encryption and can be easily reversed or decoded, exposing sensitive data.
```

2024-10-18 04:27 UTC, sushi2k commented on weaknesses/MASVS-CRYPTO/MASWE-0020.md
> +- It is recommended to use secure modes of Operation like CBC (Cipher Block Chaining).
```suggestion
- For example it is recommended to use secure modes of operations like GCM (Galois/Counter Mode) mode for AES with 256-bit keys, providing both encryption and authentication.
```

2024-10-18 04:27 UTC, sushi2k commented on weaknesses/MASVS-CRYPTO/MASWE-0020.md
> +- Always use modern, well-established cryptographic libraries and APIs that follow best practices for entropy generation and key management.
```suggestion
- Always use modern, well-established cryptographic libraries in mobile apps that follow best practices and offer cryptographic algorithms that are aligned with the recommendations by NIST.
```

2024-10-19 15:21 UTC, cpholguera requested changes

2024-10-19 15:21 UTC, cpholguera commented on tests-beta/android/MASVS-CRYPTO/MASTG-TEST-0211.md
> +title: Weak Encryption
This test is the iOS counterpart of MASTG-TEST-0210. Therefore we should title it the same way.
```suggestion
title: Weak Encryption Algorithms
```

2024-10-19 15:21 UTC, cpholguera commented on tests-beta/android/MASVS-CRYPTO/MASTG-TEST-0211.md
> +In this test case, we will look for the use of weak encryption in Android applications. To do this, we need to focus on the cryptographic implementations of algorithm such as DES, 3DES,Weak encryptio
This needs to be more elaborate, similar to  https://mas.owasp.org/MASTG/tests-beta/android/MASVS-CRYPTO/MASTG-TEST-0208/

Be careful with missing whitespace and ensure code elements are enclosed in backticks, e.g., `Cipher`

Also, try to use the `refs` we included in MASWE-0020 wherever possible as inline links for the text. Especially the ones from Support Google and Developer Android.

2024-10-19 15:25 UTC, cpholguera requested changes

2024-10-19 15:25 UTC, cpholguera commented on demos/android/MASVS-CRYPTO/MASTG_DEMO-0016/MASTG-DEMO-0016.md
> +title: Weak Encryption
To go inline with MAST-DEMO-0018
```suggestion
title: Uses of Insecure Encryption Algorithms in Cipher with se grep
```

2024-10-21 13:13 UTC, cpholguera commented
Thank you very much @sk3l10x1ng!

2024-11-05 14:23 UTC, sk3l10x1ng commented
@cpholguera @sushi2k, request changes have been done

2024-12-06 07:49 UTC, cpholguera commented
@sk3l10x1ng any news on this? Thanks!

2024-12-06 08:15 UTC, sk3l10x1ng commented
@cpholguera  will work on the request changes

2024-12-06 16:57 UTC, cpholguera commented
Thank you!

2024-12-19 10:35 UTC, sk3l10x1ng commented on tests-beta/android/MASVS-CRYPTO/MASTG-TEST-0211.md
> +title: Weak Encryption Algorithms
@cpholguera  does this file need to be completely removed or only remove the DES algorithm section?

2024-12-19 10:35 UTC, sk3l10x1ng commented on demos/android/MASVS-CRYPTO/MASTG_DEMO-0016/MASTG-DEMO-0016.md
> +title: Uses of Insecure Encryption Algorithms in Cipher with semgrep
- do we need to create new Demo file for  `title: Uses of Insecure Encryption Modes in Cipher with semgrep` or make changes to the existing one.
- The `test:MASTG-TEST-0231` point to [Reference to logging of APIs](https://github.com/OWASP/owasp-mastg/blob/master/tests-beta/android/MASVS-STORAGE/MASTG-TEST-0231.md).

2024-12-20 12:25 UTC, cpholguera commented on demos/android/MASVS-CRYPTO/MASTG_DEMO-0016/MASTG-DEMO-0016.md
> +test: MASTG-TEST-0211
This can point to the existing test 
```suggestion
test: MASTG-TEST-0221
```

2024-12-20 12:26 UTC, cpholguera commented on demos/android/MASVS-CRYPTO/MASTG_DEMO-0016/MASTG-DEMO-0016.md
> +title: Uses of Insecure Encryption Algorithms in Cipher with semgrep
The ID of the "Weak Encryption Modes" has changed to MASTG-TEST-0232  https://mas.owasp.org/MASTG/tests-beta/android/MASVS-CRYPTO/MASTG-TEST-0232/

You may add a new demo pointing to that test or do it on a separate PR.

You can keep this demo with the changes indicated below.

2024-12-20 12:27 UTC, cpholguera commented on demos/android/MASVS-CRYPTO/MASTG_DEMO-0016/MASTG-DEMO-0016.md
> +The rule has identified five instances in the code file where an insecure encryption is used. The specified line numbers can be located in the original code for further investigation and remediation.
```suggestion
The rule has identified five instances in the code file where insecure encryption algorithms are used.
```

2025-01-15 11:11 UTC, sk3l10x1ng commented
@cpholguera I've completed the demo locally,  I will push the commits today

2025-01-15 11:12 UTC, sk3l10x1ng commented
> @sk3l10x1ng we still have some requested changes here, do you have any news?


I've completed the demo locally, I will push the commits to the pull request

2025-01-16 16:05 UTC, sk3l10x1ng commented
@cpholguera I've added a new demo file. Please review it

2025-01-16 18:17 UTC, cpholguera commented
Hi @sk3l10x1ng,

I still can see only one demo, unfortunately. Could you please double check?

The following demos (each in its own folder) are expected:

- Uses of Insecure Encryption Algorithms in Cipher with semgrep
- Uses of Insecure Encryption Modes in Cipher with semgrep

This would include 2 separate semgrep files.

2025-01-17 11:55 UTC, sk3l10x1ng commented
> Hi @sk3l10x1ng,
> 
> I still can see only one demo, unfortunately. Could you please double check?
> 
> The following demos (each in its own folder) are expected:
> 
> * Uses of Insecure Encryption Algorithms in Cipher with semgrep
> * Uses of Insecure Encryption Modes in Cipher with semgrep
> 
> This would include 2 separate semgrep files.

updated the pull  request with two demos

2025-01-17 11:57 UTC, cpholguera commented
I can see them now, thank you!

2025-01-17 12:42 UTC, cpholguera requested changes

2025-01-17 12:42 UTC, cpholguera commented on weaknesses/MASVS-CRYPTO/MASWE-0020.md
> +- **Use of Deprecated Algorithms** : Relying on outdated or weak cryptographic algorithms can allow threat actors to attack the cipher text, key or exploit known vulnerabilities in the algorithm, for
```suggestion
- **Use of Deprecated Algorithms** : Relying on outdated or weak encryption algorithms can allow threat actors to attack the cipher text, key or exploit known vulnerabilities in the algorithm, for example through brute force attacks.
```

2025-01-17 12:42 UTC, cpholguera commented on demos/android/MASVS-CRYPTO/MASTG-DEMO-0022/MASTG-DEMO-0022.md
> +### Sample
Add short sample description

2025-01-17 12:42 UTC, cpholguera commented on demos/android/MASVS-CRYPTO/MASTG_DEMO-0016/MASTG-DEMO-0016.md
> +### Sample
Add short sample description

2025-01-17 12:42 UTC, cpholguera commented on demos/android/MASVS-CRYPTO/MASTG-DEMO-0022/MASTG-DEMO-0022.md
> +The rule has identified five instances in the code file where an insecure encryption is used. The specified line numbers can be located in the original code for further investigation and remediation.
The line numbers are from the reversed code.

2025-01-17 12:42 UTC, cpholguera commented on demos/android/MASVS-CRYPTO/MASTG_DEMO-0016/MASTG-DEMO-0016.md
> +Review each of the reported instances. The following configuration modes will implies the usage of insecure AES/ECB:
```suggestion
The test fails since the output contains several instances of the ECB mode of AES:
```

2025-01-17 12:42 UTC, cpholguera commented on demos/android/MASVS-CRYPTO/MASTG_DEMO-0016/MASTG-DEMO-0016.md
> +The rule has identified five instances in the code file where insecure encryption algorithms are used.
```suggestion
The rule has identified five instances in the code where insecure encryption modes are used.
```

2025-01-17 12:42 UTC, cpholguera commented on demos/android/MASVS-CRYPTO/MASTG-DEMO-0022/MASTG-DEMO-0022.md
> +The reported instances include:
```suggestion
The test fails since several instances of weak encryption algorithms were found:
```

2025-01-17 12:42 UTC, cpholguera commented on demos/android/MASVS-CRYPTO/MASTG_DEMO-0016/MASTG-DEMO-0016.md
> +code: [java]
```suggestion
code: [kotlin]
```

2025-01-17 12:42 UTC, cpholguera commented on demos/android/MASVS-CRYPTO/MASTG-DEMO-0022/MASTG-DEMO-0022.md
> +code: [java]
```suggestion
code: [kotlin]
```

2025-01-17 12:42 UTC, cpholguera commented on rules/mastg-android-weak-encryption.yaml
Rename to ...weak-encryption-algorithms.yaml

2025-01-17 12:42 UTC, cpholguera commented on rules/mastg-android-weak-encryption.yaml
> +      summary: This rule looks for weak encryption algorithm like DES, 3DES in use.
```suggestion
      summary: This rule looks for weak encryption algorithms such as DES, 3DES.
```

2025-01-17 12:42 UTC, cpholguera commented on rules/mastg-android-weak-encryption.yaml
> +    message: Weak encryption like DES,3DES are in use.
```suggestion
    message: [MASVS-CRYPTO-1] Weak encryption algorithms found in use.
```

2025-01-17 12:42 UTC, cpholguera commented on rules/mastg-android-weak-encryption-modes.yaml
> +    message: Weak encryption modes
```suggestion
    message: [MASVS-CRYPTO-1] Weak encryption modes found in use.
```

2025-01-17 12:42 UTC, cpholguera commented on rules/mastg-android-weak-encryption-modes.yaml
> +    metadata:
Move before message

2025-01-17 12:42 UTC, cpholguera commented on rules/mastg-android-weak-encryption-modes.yaml
> +      summary: This rule looks for weak encryption mode like AES/ECB/NoPadding,
Update to be one line:

This rule looks for weak encryption modes such as AES-ECB.

2025-01-17 12:42 UTC, cpholguera commented on demos/android/MASVS-CRYPTO/MASTG_DEMO-0016/run.sh
After all other changes were made. Rerun and push new outputs

2025-01-17 12:42 UTC, cpholguera commented on demos/android/MASVS-CRYPTO/MASTG-DEMO-0022/run.sh
Update rule file name here as well.

After all other changes were made. Rerun and push new outputs

2025-02-01 09:39 UTC, cpholguera approved these changes

2025-02-01 09:40 UTC, merged