Reverse Engineer Flutter Technique
OWASP/owasp-mastg pull request #2913
Opened 2024-10-16 08:21 UTC by Datafarm-Research

Hi, My name is Sabina, and I am part of the research team at Datafarm. We have recently developed a tool called Blutter, designed to reverse engineer Flutter mobile application. We believe this tool could be highly beneficial to the cybersecurity community and are excited about the possibility of sharing it through OWASP's page.

To facilitate this, I would like to propose adding a technique document about our tool to your GitHub repository. This document would include:

    -A detailed description of Blutter
    -Its key features and use cases

If there is any additional information or clarification we can provide about Blutter, or if there are any specific features or improvements you believe would enhance its functionality for your community or organization, please feel free to contact us.

Thank you for submitting a Pull Request to the OWASP MASTG. Please make sure that:

- [ ] Your contribution is written in the 2nd person (e.g. you)
- [ ] Your contribution is written in an active present form for as much as possible.
- [ ] You have made sure that the reference section is up to date (e.g. please add sources you have used, make sure that the references to MITRE/MASVS/etc. are up to date)
- [ ] Your contribution has proper formatted markdown and/or code
- [ ] Any references to website have been formatted as [TEXT](URL “NAME”)
- [ ] You verified/tested the effectiveness of your contribution (e.g.: is the code really an effective remediation? Please verify it works!)

If your PR is related to an issue. Please end your PR test with the following line:
This PR closes #< insert number here >.

2024-10-19 16:09 UTC, cpholguera commented
Thanks @Datafarm-Research for your contribution. Please review this other PR and make sure anything that's just about the tool itself goes there, or add it after the PR is merged. This may include the description, links to installation details, benefits of using the tool over other alternatives, etc. After that, please remove such information from the technique file.

Background: We have MASTG-TOOL (tools) and MASTG-TECH (techniques). To add a technique, please follow the same style as the other technique markdown files and include the metadata as yaml.

Also, please update the filename to MASTG-TECH-0112, which is the next one available. Thank you very much!

2024-10-22 07:45 UTC, Datafarm-Research commented
Hi @cpholguera thanks so much for your support. I've made the changes to the markdown file as you suggested. When you have a moment, could you provide some guidance on how to properly include metadata using YAML syntax?

2024-10-22 11:21 UTC, cpholguera commented
Absolutely, here's an example: 

https://github.com/OWASP/owasp-mastg/blob/master/techniques/android/MASTG-TECH-0001.md?plain=1

```yaml
---
title: Accessing the Device Shell
platform: android
---
```

2024-10-22 12:11 UTC, cpholguera commented on techniques/android/MASTG-TECH-0112.md
> +Flutter is an open-source UI SDK by Google for building natively
Please do not break lines within the same paragraph. Each paragraph should be in one line (represented by one line number)

2024-10-22 12:11 UTC, cpholguera commented on techniques/android/MASTG-TECH-0112.md
> +* blutter_frida.js the Frida script template for the target application
To fix these issues you need to use `-` instead.

2024-11-22 08:59 UTC, cpholguera requested changes

2025-01-03 09:05 UTC, cpholguera commented on techniques/android/MASTG-TECH-0112.md
> +While this code is not as easy to understand as typical decompiled Java code, a lot of information is still available. At the top, we can see the name of the function (`main`), as well as the locatio
```suggestion
While this code is not as easy to understand as typical decompiled Java code, a lot of information is still available. At the top, we can see the name of the function (`main`), as well as the location of the function in the original `libapp.so` binary. The different jump instructions (`bl`) are accompanied by symbol information, making it easier to understand what the code is doing. For example, we can see that the app first makes sure that the Flutter bindings are correctly initialized (`WidgetsFlutterBinding::ensureInitialized`), followed by the initialization of the `get_secure_storage` plugin (`GetSecureStorage::init`).

```

2025-01-03 09:05 UTC, cpholguera approved these changes

2025-01-03 09:06 UTC, cpholguera commented on techniques/android/MASTG-TECH-0112.md
> +
```suggestion
```

2025-01-03 09:08 UTC, merged