Mark MASTG-TEST-0016 as covered by v2 (by @guardsquare)
OWASP/owasp-mastg pull request #3026
Opened 2024-11-04 14:40 UTC by nmsa

Thank you for submitting a Pull Request to the OWASP MASTG. Please make sure that:

- [x] Your contribution is written in the 2nd person (e.g. you)
- [x] Your contribution is written in an active present form for as much as possible.
- [x] You have made sure that the reference section is up to date (e.g. please add sources you have used, make sure that the references to MITRE/MASVS/etc. are up to date)
- [x] Your contribution has proper formatted markdown and/or code
- [x] Any references to website have been formatted as [TEXT](URL “NAME”)
- [x] You verified/tested the effectiveness of your contribution (e.g.: is the code really an effective remediation? Please verify it works!)

This PR closes #2947.

2024-11-04 17:45 UTC, cpholguera requested changes

2024-11-05 09:54 UTC, nmsa commented on tests/android/MASVS-CRYPTO/MASTG-TEST-0016.md
1. The suggestion does not apply anymore. The recent documentation about SecureRandom [explains that the provided seed supplements the seed, does not replace it](https://developer.android.com/reference/java/security/SecureRandomSpi?hl=en#engineSetSeed(byte[])). I was not sure where to document this.
2. Will add the missing ones.
3. Will adjust

2024-11-05 10:27 UTC, nmsa commented on tests/android/MASVS-CRYPTO/MASTG-TEST-0016.md
After checking, both CMU links (which I did not include) are currently very outdated, and their recommendations do not apply anymore. I am mentioning one of them in the mitigations, but tbh even there some of the recommendations are slightly incorrect.

2024-11-05 10:28 UTC, nmsa commented on mitigations/android-use-secure-random.md
> +The default [no-argument constructor of `SecureRandom`](https://wiki.sei.cmu.edu/confluence/display/java/MSC02-J.+Generate+strong+random+numbers "Generation of Strong Random Numbers") is usually suff
I tried to tone down the recommendation, according to what I explained in the other discussion.

2024-11-06 10:09 UTC, nmsa commented on mitigations/android-use-secure-random.md
> +`SecureRandom` documentation explains that [the provided seed supplements, rather than replacing the existing seed](https://developer.android.com/reference/java/security/SecureRandom?hl=en#setSeed(by
I included this to cover for this weird corner case, so that the mitigation explains all the relevant points.

2024-11-07 15:59 UTC, TheDauntless reviewed
A few typo/grammer fixes

2025-01-10 10:09 UTC, cpholguera approved these changes

2025-01-10 10:09 UTC, merged