Port MASTG-TEST-0083
OWASP/owasp-mastg pull request #3029
Opened 2024-11-04 17:29 UTC by pascalj

- [ ] Your contribution is written in the 2nd person (e.g. you)
- [ ] Your contribution is written in an active present form for as much as possible.
- [ ] You have made sure that the reference section is up to date (e.g. please add sources you have used, make sure that the references to MITRE/MASVS/etc. are up to date)
- [ ] Your contribution has proper formatted markdown and/or code
- [ ] Any references to website have been formatted as [TEXT](URL “NAME”)
- [ ] You verified/tested the effectiveness of your contribution (e.g.: is the code really an effective remediation? Please verify it works!)

This PR closes #3008.

2024-11-05 11:03 UTC, cpholguera requested changes

2024-11-05 15:47 UTC, pascalj commented on tests-beta/ios/MASVS-RESILIENCE/MASTG-TEST-0x83.md
> +```
Extracted it into a technique, but I can't find a good way with radare2 to print only the debug symbols. Do you have a hint?

2024-11-05 15:49 UTC, pascalj commented on tests-beta/ios/MASVS-RESILIENCE/MASTG-TEST-0x83.md
> +This test case checks for [debugging symbols](https://mas.owasp.org/MASWE/MASVS-RESILIENCE/MASWE-0093/) in all binaries contained in the app.
I added the text (and another TECH for demangling). I feel like if this should be even more elaborate, it should be its own thing in General Concepts or so?

2024-11-05 15:50 UTC, pascalj commented on tests-beta/ios/MASVS-RESILIENCE/MASTG-TEST-0x83.md
> +The output does not contain symbols marked as debug symbols.
The explaining moved into the TECH document

2024-11-06 11:49 UTC, cpholguera approved these changes

2024-11-06 11:50 UTC, merged