Port MASTG test 0019 (by @guardsquare)
OWASP/owasp-mastg pull request #3030
Opened 2024-11-04 18:49 UTC by titze

Thank you for submitting a Pull Request to the OWASP MASTG. Please make sure that:

- [x] Your contribution is written in the 2nd person (e.g. you)
- [x] Your contribution is written in an active present form for as much as possible.
- [x] You have made sure that the reference section is up to date (e.g. please add sources you have used, make sure that the references to MITRE/MASVS/etc. are up to date)
- [x] Your contribution has proper formatted markdown and/or code
- [x] Any references to website have been formatted as [TEXT](URL “NAME”)
- [x] You verified/tested the effectiveness of your contribution (e.g.: is the code really an effective remediation? Please verify it works!)

If your PR is related to an issue. Please end your PR test with the following line:
This PR closes #2959.

2024-11-05 16:38 UTC, cpholguera requested changes

2024-11-05 17:50 UTC, titze commented on tests-beta/android/MASVS-NETWORK/MASTG-TEST-0x19-1.md
> +The test case fails if any HTTP URLs are used for communication.
See other comments, I think we have a different understanding of this test :)

2024-11-05 17:50 UTC, titze commented on tests-beta/android/MASVS-NETWORK/MASTG-TEST-0x19-5.md
> +You can use one of the following approaches:
Not added yet, how would you use Frida for this? I only know SSL-traffic dumping or removing pinning with Frida.

2024-11-05 17:50 UTC, titze commented on tests-beta/android/MASVS-NETWORK/MASTG-TEST-0x19-2.md
Good point, I added a draft test for this.

2024-12-07 14:13 UTC, cpholguera requested changes

2024-12-07 14:13 UTC, cpholguera commented on tests-beta/android/MASVS-NETWORK/MASTG-TEST-0x19-2.md
> +`SSLSocket` does not perform hostname verification (see ["Android documentation"](https://developer.android.com/privacy-and-security/security-ssl#WarningsSslSocket)) by default. This needs to be impl
```suggestion
`SSLSocket` does not perform hostname verification by default unless the app explicitly uses [`HostnameVerifier.verify()`](https://developer.android.com/reference/javax/net/ssl/HostnameVerifier#verify(java.lang.String,%20javax.net.SSL.SSLSession)). See the ["Android documentation"](https://developer.android.com/privacy-and-security/security-ssl#WarningsSslSocket) and ["Unsafe HostnameVerifier"](https://developer.android.com/privacy-and-security/risks/unsafe-hostname) for more details.
```

2024-12-07 14:13 UTC, cpholguera commented on tests-beta/android/MASVS-NETWORK/MASTG-TEST-0x19-2.md
> +
```suggestion
```

2024-12-07 14:56 UTC, cpholguera commented on tests-beta/android/MASVS-NETWORK/MASTG-TEST-0239.md
> +weakness: MASWE-0050
TODO: add support for multiple weaknesses?
This could be also https://mas.owasp.org/MASWE/MASVS-NETWORK/MASWE-0049/

2024-12-07 15:20 UTC, cpholguera approved these changes

2024-12-07 15:20 UTC, merged