Port mastg test 0022 (by @guardsquare)
OWASP/owasp-mastg pull request #3035
Opened 2024-11-05 14:11 UTC by titze

Thank you for submitting a Pull Request to the OWASP MASTG. Please make sure that:

- [x] Your contribution is written in the 2nd person (e.g. you)
- [x] Your contribution is written in an active present form for as much as possible.
- [x] You have made sure that the reference section is up to date (e.g. please add sources you have used, make sure that the references to MITRE/MASVS/etc. are up to date)
- [x] Your contribution has proper formatted markdown and/or code
- [x] Any references to website have been formatted as [TEXT](URL “NAME”)
- [x] You verified/tested the effectiveness of your contribution (e.g.: is the code really an effective remediation? Please verify it works!)

If your PR is related to an issue. Please end your PR test with the following line:
This PR closes #2958.

2025-02-15 06:26 UTC, sushi2k requested changes
Thank you for the new test cases and the PR @titze! Please check the suggestions below.

2025-02-15 06:26 UTC, sushi2k commented on tests-beta/android/MASVS-NETWORK/MASTG-TEST-0x22-1.md
> +Chapter [Certificate pinning without Android Network Security Configuration]("../../../Document/0x05g-Testing-Network-Communication.md#certificate-pinning-without-android-network-security-configurati
```suggestion
```

If we remove it in the document, let's also remove the reference here.

2025-02-15 06:26 UTC, sushi2k commented on tests-beta/android/MASVS-NETWORK/MASTG-TEST-0x22-1.md
> +The goal of this test is to check if any certificate pinning exists.
```suggestion
The goal of this test is to verify if any certificate pinning implementation is present in the code.
```

2025-02-15 06:26 UTC, sushi2k commented on tests-beta/android/MASVS-NETWORK/MASTG-TEST-0x22-1.md
> +- Pinning a certificate with a custom `TrustManager`,
```suggestion
- Pinning a certificate with a custom `TrustManager` (which should be avoided and the NSC should be used instead),
```

2025-02-15 06:26 UTC, sushi2k commented on tests-beta/android/MASVS-NETWORK/MASTG-TEST-0x22-1.md
> +    Since there are many different ways to achieve certificate pinning in the code, checking statically if the application performs pinning might not reveal all such locations. To make sure certifica
```suggestion
    Since there are many different ways to achieve certificate pinning in the code, checking statically if the application performs pinning might not reveal all such locations. To make sure certificates are pinned for all relevant connections, additional dynamic analysis need to be performed.
```

2025-02-15 06:26 UTC, sushi2k commented on tests-beta/android/MASVS-NETWORK/MASTG-TEST-0x22-1.md
> +    Since there are many different ways to achieve certificate pinning in the code, checking statically if the application performs pinning might not reveal all such locations. To make sure certifica
Dynamic analysis is a must to effectively test Certificate Pinning.

2025-02-15 06:26 UTC, sushi2k commented on tests-beta/android/MASVS-NETWORK/MASTG-TEST-0x22-2.md
> +id: MASTG-TEST-0x22-2
Could you please update each test and give it a unique ID like here: https://github.com/OWASP/owasp-mastg/tree/master/tests-beta/android/MASVS-NETWORK. This means also changing the filename accordingly.

2025-02-15 06:26 UTC, sushi2k commented on tests-beta/android/MASVS-NETWORK/MASTG-TEST-0x22-3.md
> +id: MASTG-TEST-0x22-3
Could you please update each test and give it a unique ID like here: https://github.com/OWASP/owasp-mastg/tree/master/tests-beta/android/MASVS-NETWORK. This means also changing the filename accordingly.

2025-02-15 06:26 UTC, sushi2k commented on tests-beta/android/MASVS-NETWORK/MASTG-TEST-0x22-2.md
> +Apps can configure expiration dates for pinned certificates in the [Network Security Configuration]("../../../Document/0x05g-Testing-Network-Communication.md#certificate-pinning"). After the expirati
```suggestion
Apps can configure expiration dates for pinned certificates in the [Network Security Configuration]("../../../Document/0x05g-Testing-Network-Communication.md#certificate-pinning"). After the expiration date, the pin is no longer used and all installed CAs for that domain are trusted.
```

2025-02-15 06:26 UTC, sushi2k commented on tests-beta/android/MASVS-NETWORK/MASTG-TEST-0x22-3.md
> +There are various ways how [certificate pinning]("../../../Document/0x05g-Testing-Network-Communication.md#certificate-pinning-without-android-network-security-configuration") can be done for an appl
```suggestion
```

If we remove it in the document, let's also remove the reference here.

2025-02-15 06:26 UTC, sushi2k commented on tests-beta/android/MASVS-NETWORK/MASTG-TEST-0x22-3.md
> +The goal of this test case is to dynamically check if the connection to a server can be intercepted using a [Man-in-the-Middle attack]("../../../Document/0x04f-Testing-Network-Communication.md#mitm-a
```suggestion
The goal of this test case is to dynamically check if the connection to a server can be intercepted using a [Machine-in-the-Middle attack]("../../../Document/0x04f-Testing-Network-Communication.md#mitm-attack). If this is possible, it means that the certificate is not pinned correctly or not pinned at all.
```

2025-02-17 14:07 UTC, titze commented on tests-beta/android/MASVS-NETWORK/MASTG-TEST-0x22-3.md
> +There are various ways how [certificate pinning]("../../../Document/0x05g-Testing-Network-Communication.md#certificate-pinning-without-android-network-security-configuration") can be done for an appl
I think the text itself does make sense, but if the link is gone, it makes sense to remove that.

2025-02-17 14:11 UTC, titze commented on Document/0x05g-Testing-Network-Communication.md
> +#### Hybrid Applications
Makes sense.

2025-02-17 14:14 UTC, titze commented on Document/0x05g-Testing-Network-Communication.md
> +### Certificate pinning without Android Network Security Configuration
For Android 7.0 I agree.

But what about other communication libraries like `okhttp`? I think it would be valuable to read about those, and that you can configure this differently for them, wdyt?

2025-02-18 12:31 UTC, cpholguera commented on Document/0x05g-Testing-Network-Communication.md
> +### Certificate pinning without Android Network Security Configuration
I agree we should keep the mention. Maybe this wasn't clear due to how the section is currently structured: it's a subsection of "### Android Network Security Configuration"

I think we should have a dedicated section: "### Certificate Pinning"

And have subsections for each method.

2025-02-18 12:38 UTC, cpholguera commented on Document/0x05g-Testing-Network-Communication.md
> +### Certificate pinning without Android Network Security Configuration
I asked perplexity to draft one for us, it's nice because it also includes one method we don't have here yet: TrustManager, and more.

@titze could you use this as reference to rework this section? (Carefully review and rewrite as needed since this is fully AI generated; the markdown header levels also don't match). Recommendations shouldn't be here, consider reviewing the corresponding MASWE and creating a new MASTG-BEST-xxxx to capture them and link from the tests.


--------


# Certificate Pinning  

Certificate pinning is a critical security mechanism employed in Android applications to safeguard against man-in-the-middle (MITM) attacks by ensuring that the app communicates exclusively with servers possessing predefined cryptographic credentials[1][3]. While effective when implemented correctly, variations in implementation methodologies can introduce vulnerabilities, particularly when developers misuse platform-specific APIs or third-party libraries[2][4]. Below is an analysis of common implementation approaches, their security implications, and recommendations for robust deployment.  

## Implementation Methods for Certificate Pinning in Android  

### Network Security Configuration (API 24+)  
Introduced in Android Nougat (API 24), the network security configuration file (`network_security_config.xml`) provides a declarative method for certificate pinning without requiring extensive custom code[3]. Developers specify public key hashes (pins) for trusted domains directly in XML, allowing the Android operating system to validate server certificates during the TLS handshake. This method is inherently secure because it leverages the OS’s certificate validation routines, ensuring that only the cleaned certificate chain—free of attacker-injected certificates—is evaluated against the pins[3]. For example, pins derived from a server’s public key remain valid even if the certificate is reissued with the same key, reducing maintenance overhead[3].  

### OkHttp Library  
The OkHttp library is widely used for certificate pinning in Android due to its built-in `CertificatePinner` class, which enables developers to pin public key hashes or certificate signatures[1][3]. When configured correctly—by pinning to intermediate or root certificates rather than leaf certificates—OkHttp provides robust protection against MITM attacks. However, insecure implementations arise when developers hardcode leaf certificate hashes, which become invalid upon certificate rotation, necessitating frequent app updates[3]. Additionally, older versions of OkHttp were vulnerable to chain-cleaning flaws if they relied on `getPeerCertificates()`, which returns server-sent certificates rather than the validated chain[2]. Upgrading to the latest OkHttp version and pinning to public keys mitigates these risks[2].  

### TrustKit for Backward Compatibility  
For Android versions prior to API 24, the TrustKit library offers a backward-compatible solution by integrating certificate pinning into the app’s network layer[3]. TrustKit validates pins against the cleaned certificate chain and supports report-uri functionality to notify developers of pin validation failures. However, improper configuration—such as enabling non-default options like CA pinning—can reintroduce vulnerabilities akin to custom implementations[2]. For instance, the PhoneGap SSL Certificate Checker plugin’s CA-pinning feature was found to be bypassable until patched[2].  

### Custom Implementations Using HttpsURLConnection  
Developers occasionally implement certificate pinning manually by overriding `TrustManager` or `HostnameVerifier` in `HttpsURLConnection`[1][2]. This approach is highly error-prone, as it often involves directly inspecting server-sent certificates via `getPeerCertificates()`, which returns unvalidated chains that attackers can manipulate[2]. For example, an attacker could present a malicious certificate chain containing a trusted root CA, causing the app to mistakenly validate a rogue leaf certificate[2]. Secure custom implementations require reconstructing the OS-validated certificate chain, a complex process prone to implementation errors[2].  

### Vulnerable Third-Party Libraries  
Third-party libraries like older versions of the Secure-HTTP Cordova plugin or misconfigured PhoneGap plugins historically introduced vulnerabilities by mishandling certificate chains[2]. These libraries often exposed non-default configuration options that, when enabled, allowed attackers to bypass pinning by injecting untrusted certificates into the chain. Developers must audit third-party libraries for adherence to chain-validation best practices and prefer those leveraging the Android Keystore system for pinning[2].  

## Recommendations for Secure Certificate Pinning

1. **Prefer Network Security Configuration**: For apps targeting API 24+, use the built-in `network_security_config.xml` to delegate pinning to the OS, minimizing human error[3].  
2. **Update Libraries Regularly**: Ensure OkHttp, TrustKit, and other third-party libraries are updated to versions that validate cleaned certificate chains[2][3].  
3. **Avoid Leaf Certificate Pinning**: Pin to public keys of intermediate or root CAs to accommodate certificate rotations without app updates[3].  
4. **Deprecate Custom Implementations**: Refactor legacy code using `HttpsURLConnection` or `TrustManager` to use vetted libraries or the network security config[2].  
5. **Monitor for Pinning Failures**: Implement report-uri endpoints or logging mechanisms to detect and respond to pin validation failures, indicative of ongoing attacks[3].  

By adhering to these practices, developers can mitigate risks associated with outdated or insecure pinning implementations while maintaining compatibility across Android versions[4].

## Citations
[1] What is Certificate Pinning? - Zimperium https://www.zimperium.com/glossary/certificate-pinning/
[2] Ineffective Certificate Pinning Implementations | Black Duck Blog https://www.blackduck.com/blog/ineffective-certificate-pinning-implementations.html
[3] Blog: Securing HTTPS with Certificate Pinning on Android - Approov https://approov.io/blog/securing-https-with-certificate-pinning-on-android
[4] modern alternatives to outdated certificate pinning practices https://blog.cloudflare.com/why-certificate-pinning-is-outdated/
[5] Mobile Development and Security: Certificate Pinning on Android https://nglogic.com/cert-pinning-android/
[6] 3 Ways How To Implement Certificate Pinning on Android - Netguru https://www.netguru.com/blog/android-certificate-pinning
[7] Certificate Pinning — Does It Help App Security? – PreEmptive https://www.preemptive.com/blog/what-is-certificate-pinning-app-security/
[8] Enhancing Security in Android Applications with SSL Pinning https://www.droidcon.com/2024/07/11/enhancing-security-in-android-applications-with-ssl-pinning/
[9] Defeating Android Certificate Pinning with Frida - HTTP Toolkit https://httptoolkit.com/blog/frida-certificate-pinning/
[10] Higher risk of no certificate pinning on mobile apps vs web apps? https://security.stackexchange.com/questions/226062/higher-risk-of-no-certificate-pinning-on-mobile-apps-vs-web-apps
[11] Android SSL certificate pinning to prevent Man-in-the-middle attack https://blog.ostorlab.co/android-ssl-pinning.html
[12] What is the best way to implement SSL Pinning? : r/androiddev https://www.reddit.com/r/androiddev/comments/uuie96/what_is_the_best_way_to_implement_ssl_pinning/
[13] Certificate Pinning - What it Is, its Benefits, and Drawbacks https://www.sapphire.net/blogs-press-releases/certificate-pinning/
[14] TLS Certificate Security for Android | Guardsquare https://www.guardsquare.com/blog/insecure-tls-certificate-checking-in-android-apps
[15] The problem with certificate pinning | SSLs.com Blog https://www.ssls.com/blog/the-problem-with-certificate-pinning/
[16] Security with network protocols - Android Developers https://developer.android.com/privacy-and-se [...]

2025-02-18 14:38 UTC, titze commented on Document/0x05g-Testing-Network-Communication.md
> +### Certificate pinning without Android Network Security Configuration
I added / merged most of this into the existing doc, and cleaned it up a bit.
I did not add any recommendations, since those are already captured in https://mas.owasp.org/MASWE/MASVS-NETWORK/MASWE-0047/#mitigations.

2025-02-18 15:30 UTC, cpholguera requested changes
Hi @titze there's a problem with the PR, it now affects 240 files. Could you please recheck/fix the merging of the main branch so that only your changes are showing?

2025-02-18 17:03 UTC, titze commented
Fixed. I messed up the rebase on master...

2025-02-18 17:04 UTC, cpholguera commented
No problem, thanks so much for the fix!

2025-02-22 09:13 UTC, cpholguera requested changes

2025-02-22 13:20 UTC, cpholguera commented on Document/0x05g-Testing-Network-Communication.md
> +Developers must audit third-party libraries for adherence to chain-validation best practices and prefer those leveraging the Android Keystore system for pinning.
**TODO**: Add a short section about "Pinning in Cross-Platform Frameworks" e.g. Flutter, Xamarin, React Native, Cordova/Ionic (at least some considerations). For example Flutter supports NSC, see https://docs.flutter.dev/release/breaking-changes/network-policy-ios-android#migration-guide

2025-02-22 13:22 UTC, cpholguera commented on Document/0x05g-Testing-Network-Communication.md
> +Developers must audit third-party libraries for adherence to chain-validation best practices and prefer those leveraging the Android Keystore system for pinning.
**TODO**: Add a short section about "Pinning in Cross-Platform Frameworks" e.g. Flutter, Xamarin, React Native, Cordova/Ionic (at least some considerations). For example Flutter supports NSC, see https://docs.flutter.dev/release/breaking-changes/network-policy-ios-android#migration-guide

2025-02-22 19:01 UTC, sushi2k reviewed
One small change from my side. Otherwise this looks good to me. 

Thank you for the work @titze  and the suggestions @cpholguera!

2025-02-23 05:11 UTC, sushi2k commented on tests-beta/android/MASVS-NETWORK/MASTG-TEST-0242.md
> +The goal of this test case is to dynamically check if the connection to a server can be intercepted using a [Man-in-the-Middle attack]("../../../Document/0x04f-Testing-Network-Communication.md#mitm-a
```suggestion
The goal of this test case is to dynamically check if the connection to a server can be intercepted using a [Machine-in-the-Middle attack]("../../../Document/0x04f-Testing-Network-Communication.md#mitm-attack). If this is possible, it means that the certificate is not pinned correctly or not pinned at all.
```

2025-02-23 05:12 UTC, sushi2k reviewed
MiTM change

2025-02-23 07:53 UTC, cpholguera commented on Document/0x05g-Testing-Network-Communication.md
> +Certificate pinning can be implemented manually by overriding `TrustManager` or `HostnameVerifier` in [`HttpsURLConnection`](https://developer.android.com/reference/java/net/HttpURLConnection). This
This text is going to be replaced with the suggestion from below so I'll resolve

2025-02-24 09:17 UTC, titze commented on tests-beta/android/MASVS-NETWORK/MASTG-TEST-0242.md
> +The goal of this test case is to dynamically check if the connection to a server can be intercepted using a [Man-in-the-Middle attack]("../../../Document/0x04f-Testing-Network-Communication.md#mitm-a
@sushi2k What is the reason for this change proposal? Imo, "MITM" is a defined term, which I don't think we should redefine?

2025-02-24 09:45 UTC, titze commented on Document/0x05g-Testing-Network-Communication.md
> +The Network Security Configuration can be used to pin [declarative certificates](https://developer.android.com/training/articles/security-config.html#CertificatePinning) to specific domains. This is
> It applies to all network traffic within the app

this is not completely true, the NSC only applies to connections done through the Android stack. Communication via low level APIs (e.g. from native code) do not take this into account.

2025-02-24 11:38 UTC, titze commented on Document/0x05g-Testing-Network-Communication.md
> +The Network Security Configuration can be used to pin [declarative certificates](https://developer.android.com/training/articles/security-config.html#CertificatePinning) to specific domains. This is
I changed this to:

>The **Network Security Configuration (NSC)** is the preferred and recommended way to implement certificate pinning in Android, as it provides a declarative, maintainable, and secure approach without requiring code changes. It applies to all network traffic managed by the Android framework within the app, including `HttpsURLConnection`-based connections and `WebView` requests (unless a custom `TrustManager` is used). For communication from native code, NSC does not apply, and other mechanisms need to be considered.

2025-02-24 13:21 UTC, cpholguera commented
Excellent, thanks for the updates! I'm reviewing the tests now and will post my suggestions soon.

2025-02-24 15:00 UTC, cpholguera commented on tests-beta/android/MASVS-NETWORK/MASTG-TEST-0242.md
> +The output should contain a list domains, for which the interception was successful.
```suggestion
The output should contain a list of domains for which the interception was successful.
```

2025-02-24 15:07 UTC, cpholguera commented on tests-beta/android/MASVS-NETWORK/MASTG-TEST-0242.md
> +The test case fails if any relevant domain was intercepted.
What about...?
 
```suggestion
The test fails if any **security-sensitive domain** was intercepted.
```

We could add a new prerequisite and link to it here. As in https://github.com/OWASP/owasp-mastg/blob/master/prerequisites/identify-security-relevant-contexts.md

For example (**REVIEW, AI generated**):

### Identifying Security-Sensitive Relevant Domains

#### **What is a Security-Sensitive Relevant Domain?**

A relevant domain is any endpoint where failing to enforce certificate pinning could expose sensitive data or compromise security. This typically includes:
- **Authentication endpoints** (e.g., login APIs, OAuth/token exchanges)
- **Endpoints handling sensitive user data** (e.g., financial transactions, personal data transfers)
- **Endpoints that initiate encrypted tunnels** (e.g., VPN, secure messaging services)
- **Internal API endpoints** used for secure app-server communication

#### **What is NOT a Security-Sensitive Relevant Domain?**

- **Third-party CDNs or analytics services** that the app does not control

2025-02-24 15:07 UTC, cpholguera commented on Document/0x05g-Testing-Network-Communication.md
> +- The framework might support NSC. This is the case for Flutter apps on Android, but the NSC needs to be enabled in the `AndroidManifest`. See the [Flutter documentation](https://docs.flutter.dev/rel
It seems this "feature" as well as the support for `android:usesCleartextTraffic="true"` in the manifest was reverted in Flutter 2.2: https://docs.flutter.dev/release/breaking-changes#reverted-change-in-2-2

According to this comment it's still kind of there: https://github.com/flutter/flutter/issues/106678#issuecomment-1169127260 but I'm not sure what's going on.

It looks like the way to do pinning in Flutter is via `securityContext.setTrustedCertificatesBytes` or `securityContext.setTrustedCertificates`

See https://api.flutter.dev/flutter/dart-io/SecurityContext/setTrustedCertificatesBytes.html

2025-02-25 07:03 UTC, titze commented on tests-beta/android/MASVS-NETWORK/MASTG-TEST-0241.md
> +The goal of this test is to check if any expiration date is in the past.
sounds good, thanks!

2025-02-25 07:08 UTC, titze commented on tests-beta/android/MASVS-NETWORK/MASTG-TEST-0240.md
> +title: Missing Certificate Pinning in Code
I created a task, this PR is getting quite big.
https://github.com/OWASP/owasp-mastg/issues/3183

2025-02-25 07:16 UTC, titze commented on tests-beta/android/MASVS-NETWORK/MASTG-TEST-0242.md
> +title: Missing Certificate Pinning in Network Traffic
@cpholguera not sure I understand what you mean. The link you mention explains how to _deactivate_ pinning using Frida etc. How would that help identifying if pinning is done / done correctly?

What could be (somewhat) helpful, is to try the Frida scripts to see where it attaches, to then statically analyse those locations (relating to the to-be-created test for #3183).

Am I missing something?

2025-02-25 07:17 UTC, titze commented on tests-beta/android/MASVS-NETWORK/MASTG-TEST-0242.md
> +3. Extract all domains which were intercepted.
@cpholguera which clues do you have in mind? 
The way I did this before was to just look at the intercepting proxy, logcat from the device never added anything too useful for this particular test.

2025-02-25 07:31 UTC, titze commented on tests-beta/android/MASVS-NETWORK/MASTG-TEST-0242.md
> +The test case fails if any relevant domain was intercepted.
@cpholguera I agree this would benefit a lot from a definition. Maybe sth to discuss in our next meeting, I don't think this is easy to define.

Imo, security-sensitive depends a lot on the app context, but also on the test / weakness itself. I could imagine certificate pinning being mandatory for L2 for specific domains, but it certainly shouldn't be mandatory for all domains for L1.

In the AI generated text, the 3rd party or analytics service is already not ideal imo. Whilst I agree with this for certificate pinning, I don't think analytics services are by default not security sensitive. E.g., thinking about GDPR, I can imagine personal identifiers being sent there, which need to be handled with care and are security sensitive...

2025-03-03 20:00 UTC, cpholguera requested changes

2025-03-03 20:00 UTC, cpholguera commented on tests-beta/android/MASVS-NETWORK/MASTG-TEST-0242.md
> +3. Extract all domains which were intercepted.
Doesn't it output a `javax.net.ssl.SSLHandshakeException` / `java.security.cert.CertPathValidatorException` when pinning fails due to the presence of the MITM?
```

2025-03-03 20:00 UTC, cpholguera commented on tests-beta/android/MASVS-NETWORK/MASTG-TEST-0242.md
> +The test case fails if any relevant domain was intercepted.
We leave this for a separate PR.

2025-03-03 20:01 UTC, cpholguera commented
@titze this is almost ready, just a couple of suggestions and we can merge. Thank you!

2025-03-04 07:04 UTC, titze commented on tests-beta/android/MASVS-NETWORK/MASTG-TEST-0242.md
> +3. Extract all domains which were intercepted.
The log message largely depends on how this is implemented. There might be some, but if the app follows best practise, it would not give an attacker any information in the logs.
The log message itself could also mean very different things. Does it mean the connection succeeds even in the precence of a Mitm, or that it was not established.
Imo, the real test is in the proxy itself: were you able to intercept, or not.

2025-03-04 07:06 UTC, titze commented on Document/0x05g-Testing-Network-Communication.md
> +Several approaches to certificate pinning exist, depending on the app's API level and the libraries used. Below, we highlight the most common methods. For a deeper dive into the specific implementati
@cpholguera aren't those considerations too broad? If no signature checks and other runtime protections are in place, I can always modify the app, and modify parts to make it less secure.

2025-03-04 07:35 UTC, cpholguera commented on tests-beta/android/MASVS-NETWORK/MASTG-TEST-0242.md
> +The goal of this test case is to observe whether a [MITM attack]("../../../Document/0x04f-Testing-Network-Communication.md#mitm-attack) can intercept HTTPS traffic from the app. A successful MITM int
```suggestion
The goal of this test case is to observe whether a [MITM attack]("../../../Document/0x04f-Testing-Network-Communication.md#intercepting-network-traffic-through-mitm) can intercept HTTPS traffic from the app. A successful MITM interception indicates that the app is either not using certificate pinning or implementing it incorrectly.
```

2025-03-04 07:43 UTC, cpholguera commented on Document/0x05g-Testing-Network-Communication.md
> +Several approaches to certificate pinning exist, depending on the app's API level and the libraries used. Below, we highlight the most common methods. For a deeper dive into the specific implementati
That's right, and intentional. This is to let the reader know that it can and will be bypassed (in a pentest, or by an attacker if they really want to look at the traffic; if other protections are in place, they will also try/have to remove them first).

We can clarify this further, of course, what would you suggest?

2025-03-04 07:43 UTC, cpholguera commented on Document/0x05g-Testing-Network-Communication.md
>  ### Security Provider
```suggestion

### Security Provider
```

2025-03-04 07:46 UTC, titze commented on Document/0x05g-Testing-Network-Communication.md
> +Several approaches to certificate pinning exist, depending on the app's API level and the libraries used. Below, we highlight the most common methods. For a deeper dive into the specific implementati
If that's intentional, I like your proposal. I just wanted to point out that - if I am able to modify the application, I can ofc make it less secure. But it probably is a good thing to repeat that to the reader :)

2025-03-04 07:53 UTC, cpholguera commented on tests-beta/android/MASVS-NETWORK/MASTG-TEST-0242.md
> +3. Extract all domains which were intercepted.
I think you're right, but I also think it may be helpful to at least mention this as a testing tip, as the original test did. If you're trying to intercept and you get these log messages, that can be useful info. Also, if I'm not mistaken, some of these logs are coming from the system. Also, if the app doesn't follow best practices, even better for you as a tester.

I suggest we add it as a test tip, and once the demos are in place, if it's not helpful, we can remove it.

2025-03-04 08:06 UTC, cpholguera commented on tests-beta/android/MASVS-NETWORK/MASTG-TEST-0242.md
> +1. Set up an intercepting proxy, for example @MASTG-TOOL-0077 or @MASTG-TOOL-0097.
```suggestion
1. Set up an interception proxy, see @MASTG-TECH-0011.
```

2025-03-04 08:41 UTC, cpholguera commented on tests/android/MASVS-NETWORK/MASTG-TEST-0022.md
> +covered_by: [MASTG-TEST-0x22-1,MASTG-TEST-0x22-2,MASTG-TEST-0x22-3]
```suggestion
covered_by: [MASTG-TEST-0242, MASTG-TEST-0243, MASTG-TEST-0244]
```

2025-03-04 08:49 UTC, cpholguera approved these changes
Thanks a lot @titze!!

2025-03-04 08:53 UTC, merged