Port MASTG-TEST-0006 (by @guardsquare)
OWASP/owasp-mastg pull request #3055
Opened 2024-11-07 14:08 UTC by serek8

This PR closes #2936.

TODO: @cpholguera we still need to find a relevant MASWE for it.

2024-11-07 15:08 UTC, cpholguera commented on tests-beta/android/MASVS-PRIVACY/MASTG-TEST-0x06.md
> +id: MASTG-TEST-0x06
maybe https://mas.owasp.org/MASWE/MASVS-PLATFORM/MASWE-0053/?

2024-11-07 15:18 UTC, cpholguera commented on tests-beta/android/MASVS-PRIVACY/MASTG-TEST-0x06.md
> +This test checks whether your app prevents the caching of sensitive information entered into text fields. The keyboard may suggest previously entered text when typing in your app or other apps on the
```suggestion
This test checks whether your app prevents the caching of sensitive information entered into text fields. The keyboard may suggest previously entered text when typing in your app or other apps on the device. You can disable the caching mechanism for a text input by setting [`textNoSuggestions`](https://developer.android.com/reference/android/widget/TextView#attr_android:inputType:~:text=the%20performance%20reasons.-,textNoSuggestions,-80001) on it.
```

2024-11-07 15:18 UTC, cpholguera commented on tests-beta/android/MASVS-PRIVACY/MASTG-TEST-0x06.md
> +- [textWebPassword](https://developer.android.com/reference/android/widget/TextView#attr_android:inputType:~:text=_PHONE.-,text,-1)
```suggestion
- [`textPassword`](https://developer.android.com/reference/android/widget/TextView#attr_android:inputType)
- [`textVisiblePassword`](https://developer.android.com/reference/android/widget/TextView#attr_android:inputType:~:text=_URI.-,textVisiblePassword,-91)
- [`numberPassword`](https://developer.android.com/reference/android/widget/TextView#attr_android:inputType:~:text=_DECIMAL.-,numberPassword,-12)
- [`textWebPassword`](https://developer.android.com/reference/android/widget/TextView#attr_android:inputType:~:text=_PHONE.-,text,-1)
```

2024-11-07 15:18 UTC, cpholguera commented on tests-beta/android/MASVS-PRIVACY/MASTG-TEST-0x06.md
> +1. Run a static analysis tool such as @MASTG-TOOL-0018 or @MASTG-TOOL-0011 on the APK to verify if your app uses `textNoSuggestions` or the `*password` attribute.
```suggestion
1. Run a static analysis tool such as @MASTG-TOOL-0018 or @MASTG-TOOL-0011 on the APK looking for uses of any of the above attributes.
```

2024-11-07 15:18 UTC, cpholguera commented on tests-beta/android/MASVS-PRIVACY/MASTG-TEST-0x06.md
> +The test case fails if any of the text fields in your app accepts sensitive data but does not use `textNoSuggestions` or `*password` attribute.
```suggestion
The test case fails if any of the text fields in your app accepts sensitive data but do not use no-caching attributes.
```

2024-11-07 15:18 UTC, cpholguera commented on tests-beta/android/MASVS-PRIVACY/MASTG-TEST-0x06.md
> +type: [static]
```suggestion
id: MASTG-TEST-0224
type: [static]
weakness: MASWE-0053
```

2024-11-07 15:18 UTC, cpholguera commented on tests/android/MASVS-STORAGE/MASTG-TEST-0006.md
> +covered_by: [MASTG-TEST-0x06]
```suggestion
covered_by: [MASTG-TEST-0224]
```

2024-11-07 15:37 UTC, cpholguera commented on tests/android/MASVS-STORAGE/MASTG-TEST-0006.md
>  ## Overview
check below, there's some content that could go in a theory chapter and be referenced from the new test. Also the table is good to have as a table in the theory and it indicates the API levels.

2024-11-07 15:40 UTC, cpholguera requested changes

2024-11-07 15:40 UTC, cpholguera commented on tests/android/MASVS-STORAGE/MASTG-TEST-0006.md
check below, there's some content that could go in a theory chapter and be referenced from the new test. Also the table is good to have as a table in the theory and it indicates the API levels.

2024-11-07 17:51 UTC, serek8 commented on tests-beta/android/MASVS-PRIVACY/MASTG-TEST-0224.md
I added the explanation in the latest commit. PLease have a look

2024-11-07 17:53 UTC, serek8 commented on tests/android/MASVS-STORAGE/MASTG-TEST-0006.md
I added it for now to the test. Please have a look if it's ok.

2025-01-30 08:14 UTC, cpholguera requested changes

2025-01-30 08:14 UTC, cpholguera commented on tests-beta/android/MASVS-PRIVACY/MASTG-TEST-0224.md
> +## Steps
from the original test:

> Finally, check the minimum required SDK version in the Android Manifest (`android:minSdkVersion`) since it must support the used constants (for example, Android SDK version 11 is required for `textWebPassword`). Otherwise, the compiled app would not honor the used input type constants allowing keyboard caching.

Shouldn't we add this? Maybe we see the constants but the app can be installed on older OS versions where they won't apply.

2025-01-30 08:14 UTC, cpholguera commented on tests-beta/android/MASVS-PRIVACY/MASTG-TEST-0224.md
> +2. Statically search for above code attributes with @MASTG-TOOL-0018
Also from the original:

> Check the application code to verify that none of the input types are being overwritten. For example, by doing `findViewById(R.id.KeyBoardCache).setInputType(InputType.TYPE_CLASS_TEXT)` the input type of the input field `KeyBoardCache` is set to `text` reenabling the keyboard cache.

Shouldn't we also check for this here?

2025-01-30 08:14 UTC, cpholguera commented on tests-beta/android/MASVS-PRIVACY/MASTG-TEST-0224.md
> +Android apps can use XML or code to create the UI. Many apps use both techniques simultaneously. So you should test both. After unpacking the APK with @MASTG-TOOL-0011, the XML files are in `/res/lay
The section isn't super useful but just for the sake of keeping track of it. We can improve that section later.

```suggestion
Android apps can use XML or code to create the UI. Many apps use both techniques simultaneously. So you should test both. After unpacking the APK with @MASTG-TOOL-0011, the XML files are in `/res/layout` directory. You can search for the code attributes with @MASTG-TOOL-0018.

For more information you can consult the MASTG section about ["Keyboard Cache"](../../../Document/0x05d-Testing-Data-Storage.md#keyboard-cache).
```

2025-01-30 08:14 UTC, cpholguera commented on tests-beta/android/MASVS-PRIVACY/MASTG-TEST-0224.md
Do we have any demos / could you add one?

2025-03-04 13:06 UTC, serek8 commented on tests-beta/android/MASVS-PRIVACY/MASTG-TEST-0224.md
> +## Steps
Not sure if I understand. `textWebPassword` is available starting from API level 11(Android 3).

2025-03-04 13:31 UTC, serek8 commented on tests-beta/android/MASVS-PRIVACY/MASTG-TEST-0224.md
> +2. Statically search for above code attributes with @MASTG-TOOL-0018
Right, I will add it! Thanks

2025-03-05 16:21 UTC, serek8 commented on tests-beta/android/MASVS-PRIVACY/MASTG-TEST-0224.md
> +## Steps
Added in the latest commit

2025-03-23 11:24 UTC, cpholguera approved these changes

2025-03-23 11:30 UTC, merged