Port MASTG-TEST-0003 (by @guardsquare)
OWASP/owasp-mastg pull request #3059
Opened 2024-11-07 15:13 UTC by serek8

This PR closes #2935.

2024-11-07 15:46 UTC, cpholguera requested changes

2024-11-07 15:46 UTC, cpholguera commented on tests-beta/android/MASVS-STORAGE/MASTG-TEST-0x03.md
This one looks like https://mas.owasp.org/MASTG/tests-beta/android/MASVS-STORAGE/MASTG-TEST-0203/ 

if anything from the MASTG-TEST-0003 is missing in MASTG-TEST-0203 you can add it there. Or if we're missing a different aspect then it can be a new test.

2024-11-22 07:47 UTC, cpholguera commented on tests-beta/android/MASVS-STORAGE/MASTG-TEST-0x03.md
@serek8 could you please double check this? Thanks 😊

2024-11-29 09:28 UTC, serek8 commented on tests-beta/android/MASVS-STORAGE/MASTG-TEST-0x03.md
@cpholguera I think it's a similar case to External Storage tests. There are 3 tests:
1. [MASTG-TEST-0200](https://mas.owasp.org/MASTG/tests-beta/android/MASVS-STORAGE/MASTG-TEST-0200/) (dynamic test)
2. [MASTG-TEST-0201](https://mas.owasp.org/MASTG/tests-beta/android/MASVS-STORAGE/MASTG-TEST-0201/) (dynamic test)
3. [MASTG-TEST-0202](https://mas.owasp.org/MASTG/tests-beta/android/MASVS-STORAGE/MASTG-TEST-0202/) (static test)

As far as I remember we split them because we didn't want to mix static and dynamic in the past. Each test also has `type: [static/dynamic]` metadata to let the users filter out tests we are interested in. If we merge dynamic and static tests into one file, a user won't be able to filter anymore. On the other hand, `type` is an array so we can add both types to a one test, which makes it a bit blurry to decide how to treat it.

This pull request describes a static test while [MASTG-TEST-0203](https://mas.owasp.org/MASTG/tests-beta/android/MASVS-STORAGE/MASTG-TEST-0203/) describes a dynamic test. 

If you prefer, I can just extend `MASTG-TEST-0203`'s steps with a subheader for static steps from this PR but then I would also need to do the same with mitigations.

To sum up I think we should keep this PR as a separate test and assign it an appropriate `type : [static]`. Then a tester can unambiguously say they tested X tests out of Y tests if they want to cover only static tests.

2024-11-29 12:16 UTC, cpholguera commented on tests-beta/android/MASVS-STORAGE/MASTG-TEST-0x03.md
After this comment and the offline discussion: let's keep this a static test and try to keep static and dynamic separated. We'll include this in the guidelines and update existing tests.

2024-11-29 15:44 UTC, cpholguera approved these changes

2024-11-29 16:19 UTC, merged