Port MASTG-TEST-0088 (by @appknox)
OWASP/owasp-mastg pull request #3073
Opened 2024-11-21 11:40 UTC by sk3l10x1ng

PR closes #3006

2024-12-06 07:45 UTC, cpholguera commented
Could you please include a MASTG-DEMO as well using our app?

This greatly helps understanding the test, so we're going to make this a requirement for everyone from now on (unless there's a good reason to schedule it for later, e.g. due to great complexity). Thanks a lot @sk3l10x1ng!

2024-12-18 13:52 UTC, sk3l10x1ng commented
> Could you please include a MASTG-DEMO as well using our app?
> 
> This greatly helps understanding the test, so we're going to make this a requirement for everyone from now on (unless there's a good reason to schedule it for later, e.g. due to great complexity). Thanks a lot @sk3l10x1ng!

@cpholguera  Added Demo , please review it .

2025-01-03 09:55 UTC, cpholguera requested changes

2025-01-03 09:55 UTC, cpholguera commented on demos/ios/MASVS-RESILIENCE/MASTG-DEMO-0088/output.asm
update using the new code

2025-01-03 09:55 UTC, cpholguera commented on demos/ios/MASVS-RESILIENCE/MASTG-DEMO-0088/MASTestApp
update using the new code

2025-01-03 09:55 UTC, cpholguera commented on demos/ios/MASVS-RESILIENCE/MASTG-DEMO-0088/MASTG-DEMO-0088.md
> +The test fails because jailbreak detection checks implemented in the app.
```suggestion
The test passes because jailbreak detection checks are implemented in the app.
```

2025-01-03 10:37 UTC, cpholguera commented on tests/ios/MASVS-RESILIENCE/MASTG-TEST-0088.md
> +covered_by: [MASTG-TEST-0x88]
```suggestion
covered_by: [MASTG-TEST-0x88, MASTG-TEST-0x89]
```

2025-01-03 11:51 UTC, TheDauntless approved these changes

2025-01-03 11:51 UTC, TheDauntless commented on tests-beta/ios/MASVS-RESILIENCE/MASTG-TEST-0x88.md
> +The test verifies that a mobile app can detect if the iOS device it is running on is jailbroken. It does so by statically analyzing the app binary for [common jailbreak detection checks](../../../Doc
```suggestion
The test verifies that a mobile app can detect if the iOS device it is running on is jailbroken. It does so by statically analyzing the app binary for [common jailbreak detection checks](../../../Document/0x06j-Testing-Resiliency-Against-Reverse-Engineering.md#common-jailbreak-detection-checks). For example, the app may check for the presence of a third party app store (e.g. Sileo, Zebra, ...), or for the presence of certain files or directories that are indicative of a jailbroken device.
```

2025-01-03 11:51 UTC, TheDauntless commented on tests-beta/ios/MASVS-RESILIENCE/MASTG-TEST-0x88.md
> +The limitations of static analysis should be considered. It is possible that the app uses more sophisticated jailbreak detection techniques that are not detected by the tool used. In such cases, care
```suggestion
The limitations of static analysis should be considered. It is possible that the app uses more sophisticated jailbreak detection techniques that are not detected by the used tool. In such cases, careful manual reverse engineering and deobfuscation are required to identify the jailbreak detection checks.
```

2025-01-03 11:51 UTC, TheDauntless commented on tests-beta/ios/MASVS-RESILIENCE/MASTG-TEST-0x89.md
> +The test verifies that a mobile application can identify if the iOS device it is running on is jailbroken. It does so by dynamically analyzing the app binary for [common jailbreak detection checks](.
```suggestion
The test verifies that a mobile application can identify if the iOS device it is running on is jailbroken. It does so by dynamically analyzing the app binary for [common jailbreak detection checks](../../../Document/0x06j-Testing-Resiliency-Against-Reverse-Engineering.md#common-jailbreak-detection-checks) and trying to bypass them. For example, it may detect a check for the presence of certain files or directories that are indicative of a jailbroken device.
```
Removed the last sentence as the bypass angle is irrelevant. We're using the tool to collect artefacts, not to bypass a JB check

2025-01-03 11:51 UTC, TheDauntless commented on tests-beta/ios/MASVS-RESILIENCE/MASTG-TEST-0x89.md
> +The test passes if jailbreak detection is implemented and the automated jailbreak detection bypass commands are successful or at least provide useful information to help you narrow down the jailbreak
```suggestion
The test passes if the automated jailbreak detection bypass command indicates that the application is testing for known jailbreak artefacts.
```

2025-01-03 11:51 UTC, TheDauntless commented on tests-beta/ios/MASVS-RESILIENCE/MASTG-TEST-0x89.md
> +Consider that there may be other resiliency mechanisms in place that prevent the application from running, such as runtime integrity checks, so the app may still not run even if the jailbreak detecti
```suggestion
```
Would delete this. The test only requires JB detection to be implemented so we should focus on that. Even if the app only does one very basic test which is easily bypassed, this test should succeed. Whether or not you can eventually run the app is irrelevant.

2025-01-03 11:51 UTC, TheDauntless commented on tests-beta/ios/MASVS-RESILIENCE/MASTG-TEST-0x89.md
> +Even if the automated jailbreak detection bypass commands are not successful, they may provide useful information to help you narrow down the jailbreak detection checks implemented in the app.
```suggestion
```
If they give any useful info, the check would already pass.

2025-01-03 12:22 UTC, sk3l10x1ng commented on demos/ios/MASVS-RESILIENCE/MASTG-DEMO-0088/MastgTest.swift
verified on a physical device, the code works with a jailbroken vs a non-jailbroken device.

2025-01-03 12:23 UTC, sk3l10x1ng commented
@cpholguera will work on the requested changes

2025-01-03 12:41 UTC, cpholguera commented on tests-beta/ios/MASVS-RESILIENCE/MASTG-TEST-0x89.md
> +
```suggestion
```

2025-01-09 05:14 UTC, sk3l10x1ng commented on demos/ios/MASVS-RESILIENCE/MASTG-DEMO-0088/output.asm
done

2025-01-09 05:14 UTC, sk3l10x1ng commented on demos/ios/MASVS-RESILIENCE/MASTG-DEMO-0088/MASTestApp
done

2025-01-09 05:54 UTC, sk3l10x1ng commented
@cpholguera  requested changes are done

2025-01-10 09:08 UTC, cpholguera approved these changes

2025-01-10 09:09 UTC, merged

2025-01-15 10:59 UTC, cpholguera commented on tests-beta/ios/MASVS-RESILIENCE/MASTG-TEST-0241.md
@sk3l10x1ng would you mind creating a new demo for this in a separate PR?