Port MASTG-TEST-0082 (by @appknox)
OWASP/owasp-mastg pull request #3097
Opened 2024-12-16 11:36 UTC by jeel38

closes #3010

2024-12-18 09:19 UTC, cpholguera commented on tests-beta/ios/MASVS-RESILIENCE/MASTG-TEST-0x82.md
> +The test fails as the entitlement get-task-allow is true, allowing debugger attachment.
```suggestion
The test fails if the `get-task-allow` entitlement is `true`.
```

2024-12-18 09:23 UTC, cpholguera commented on tests-beta/ios/MASVS-RESILIENCE/MASTG-TEST-0x82.md
> +The test evaluates whether an iOS application is configured to allow debugging. If an app is debuggable, attackers can leverage debugging tools to reverse-engineer the application, analyse its runtim
```suggestion
The test evaluates whether an iOS application is configured to allow debugging. If an app is debuggable, attackers can leverage debugging tools (see @MASTG-TECH-0084) to analyse the runtime behaviour of the app, and potentially compromise sensitive data or functionality.
```

2024-12-18 09:25 UTC, cpholguera commented
First round of review done. Please remember to include a demo using https://github.com/cpholguera/MASTestApp-iOS

Thanks a lot @jeel38!

2025-02-03 11:28 UTC, jeel38 commented
@cpholguera Please Review it

2025-02-04 10:20 UTC, serek8 requested changes
Thanks for contribution. I added a few comments in code.

One more thingy, your demo covers 2 cases:
* detects if an app is debuggable
* detects if an app is currently being debugged

Can you split these two cases into two distinct demos and make sure this subtle difference is clear for the reader?

2025-02-04 10:20 UTC, serek8 commented on demos/ios/MASVS-RESILIENCE/MASTG-DEMO-0023/MastgTest.swift
> +                       content.contains("get-task-allow") {
I am afraid this method might cause false positives. For example, if there is a third-party code in the binary that also contains `get-task-allow`, this would trigger a false positive. It's also a bit slow to search through the whole binary, no? Can you optimise it?

2025-02-04 10:20 UTC, serek8 commented on demos/ios/MASVS-RESILIENCE/MASTG-DEMO-0023/MastgTest.swift
> +        let isDebugger = isDebuggerAttached()
Can you make such a function for each method? It would clean up the code a bit.

2025-02-04 11:56 UTC, cpholguera commented on demos/ios/MASVS-RESILIENCE/MASTG-DEMO-0023/MastgTest.swift
> +        let isDebugger = isDebuggerAttached()
Do we need this file at all? If I'm not wrong I think we just need the modified entitlements file, so that we can build the app using it, and the reversed version.

Here's the original: https://github.com/cpholguera/MASTestApp-iOS/blob/main/entitlements.plist

2025-02-04 11:58 UTC, serek8 commented on demos/ios/MASVS-RESILIENCE/MASTG-DEMO-0023/MastgTest.swift
> +        let isDebugger = isDebuggerAttached()
Reducing this demo to only one method is also ok

2025-02-14 08:58 UTC, cpholguera requested changes

2025-02-14 08:58 UTC, cpholguera commented on demos/ios/MASVS-RESILIENCE/MASTG-DEMO-0023/debuggable.r2
remove

2025-02-14 08:58 UTC, cpholguera commented on demos/ios/MASVS-RESILIENCE/MASTG-DEMO-0023/run.sh
> +r2 -q -i debuggable.r2 -A MASTestApp > output.asm
```suggestion
rabin2 -OC MASTestApp | grep -A1 get-task-allow
```

2025-02-14 08:58 UTC, cpholguera commented on demos/ios/MASVS-RESILIENCE/MASTG-DEMO-0023/output.asm
> +273 0x00011baa 0x100011baa 14  15                          ascii   get-task-allow
```suggestion
        <key>get-task-allow</key>
        <true/>
```

2025-02-14 09:00 UTC, cpholguera commented on demos/ios/MASVS-RESILIENCE/MASTG-DEMO-0023/MASTG-DEMO-0023.md
> +{{ MastgTest.swift }}
Instead of this we need the modified entitlements file, so that we can build the app using it, and the reversed version.

Here's the original: https://github.com/cpholguera/MASTestApp-iOS/blob/main/entitlements.plist

```suggestion
{{ entitlements.plist # entitlements_reversed.plist }}
```

2025-02-14 09:01 UTC, cpholguera commented on demos/ios/MASVS-RESILIENCE/MASTG-DEMO-0023/MASTG-DEMO-0023.md
> +{{ debuggable.r2 }}
```suggestion
2. Run @MASTG-TOOL-0129 with the `-OC` options to obtain the entitlements file.
```

2025-02-14 09:03 UTC, cpholguera commented on demos/ios/MASVS-RESILIENCE/MASTG-DEMO-0023/MASTG-DEMO-0023.md
> +The test passes because debugging detection checks are implemented in the app.
```suggestion
The test fails because the app is debuggable due to the `get-task-allow` entitlement being present.
```

2025-02-14 09:04 UTC, cpholguera commented on demos/ios/MASVS-RESILIENCE/MASTG-DEMO-0023/MASTG-DEMO-0023.md
> +title: Verify App is Debuggable with r2
```suggestion
title: Debuggable Entitlement Enabled in the entitlements.plist with rabin2
```

2025-02-14 09:05 UTC, cpholguera commented on tests-beta/ios/MASVS-RESILIENCE/MASTG-TEST-0x82.md
> +title: Testing Whether the App is Debuggable
```suggestion
title: Debuggable Entitlement Enabled in the entitlements.plist
```

2025-02-14 09:09 UTC, cpholguera commented on tests-beta/ios/MASVS-RESILIENCE/MASTG-TEST-0x82.md
> +weakness: MASWE-0101
MASWE-0067: Debuggable Flag Not Disabled

```suggestion
weakness: MASWE-0067
```

2025-02-14 09:09 UTC, cpholguera commented
@jeel38 we're almost there, thanks!!

2025-02-28 08:00 UTC, cpholguera commented
@jeel38 an news? Thanks

2025-03-17 11:41 UTC, jeel38 commented
@cpholguera Please review it

2025-03-17 13:26 UTC, merged