Ipa installation by @NVISOSecurity
OWASP/owasp-mastg pull request #3100
Opened 2024-12-26 13:02 UTC by TheDauntless

A cleanup of all the iOS signing / installing / running in debug mode.

I tried to be pragmatic, focussing on different techniques that work (I tested all of them, it was not a fun day) and also focussing on modern solutions rather than keep holding on to outdated ones.

2024-12-30 10:22 UTC, sushi2k requested changes
Great content @TheDauntless! Also the warnings/tips for AppSync and libimobiledevice are spot on! I've reviewed the tools, planning to do the rest today or tomorrow.

2024-12-30 11:00 UTC, TheDauntless commented on tools/ios/MASTG-TOOL-0055.md
> +!!! warning
Those are admonitions. They're not markdown, but they are part of mkdocs. There's a run_web.sh you can use to preview, or the vscode workspace.

2024-12-30 11:01 UTC, TheDauntless commented on tools/ios/MASTG-TOOL-0118.md
> +    To sign an IPA file, you will need a valid iOS developer account, either free or paid. Both types come with certain restrictions, as explained on the Sideloadly website. We recommend creating a d
Not sure I understand this comment.

2024-12-30 11:02 UTC, TheDauntless commented on tools/ios/MASTG-TOOL-0055.md
> +!!! warning
(I'm going to mark your other comments related to this syntax as resolved)

2024-12-30 11:02 UTC, TheDauntless commented
Thanks for the review so far!

2025-01-04 06:56 UTC, sushi2k reviewed
@TheDauntless reviewed more techniques, but not done yet. Thanks for the nice summary!

2025-01-04 06:56 UTC, sushi2k commented on techniques/ios/MASTG-TECH-0055.md
> +(lldb) device select 00008101-1234567890123456
```suggestion
# Select the iOS device you want to interact with
(lldb) device select 00008101-1234567890123456

```

2025-01-04 06:56 UTC, sushi2k commented on techniques/ios/MASTG-TECH-0055.md
> +783    0                                                UnCrackable Level 1
```suggestion
783    0                                                UnCrackable Level 1

```

2025-01-04 06:56 UTC, sushi2k commented on techniques/ios/MASTG-TECH-0055.md
> +Target 0: (UnCrackable Level 1) stopped.
```suggestion
Target 0: (UnCrackable Level 1) stopped.

```

2025-01-04 06:56 UTC, sushi2k commented on techniques/ios/MASTG-TECH-0055.md
> +(lldb) device select 00008101-1234567890123456
I added a few newlines so it's easier to read.

2025-01-04 06:56 UTC, sushi2k commented on techniques/ios/MASTG-TECH-0055.md
> +rida-ps -Ua
```suggestion
$ frida-ps -Ua
```

2025-01-04 06:56 UTC, sushi2k commented on techniques/ios/MASTG-TECH-0055.md
>  frida -U -n Gadget
```suggestion
$ frida -U -n Gadget
```

2025-01-04 06:56 UTC, sushi2k commented on techniques/ios/MASTG-TECH-0055.md
> +After attaching, the application will continue executing as normal.
I tested it on my iOS 17 device, worked like a charm!

2025-01-04 06:56 UTC, sushi2k commented on techniques/ios/MASTG-TECH-0055.md
> +(lldb) c
```suggestion
# Continue execution of all threads in the current process.
(lldb) c
```

2025-01-04 06:56 UTC, sushi2k commented on techniques/ios/MASTG-TECH-0055.md
> +$ lldb
```suggestion
# Execute the lldb debugger
$ lldb
```

2025-01-04 06:56 UTC, sushi2k commented on techniques/ios/MASTG-TECH-0055.md
> +(lldb) device process list
```suggestion
# Command to query the processes on a device.
(lldb) device process list
```

2025-01-04 06:56 UTC, sushi2k commented on techniques/ios/MASTG-TECH-0055.md
> +(lldb) device process attach --pid 783
```suggestion
# Command to attach to a specific process by their process ID
(lldb) device process attach --pid 783
```

2025-01-04 06:56 UTC, sushi2k commented on techniques/ios/MASTG-TECH-0055.md
> +$ idevicedebug -d run sg.vp.UnCrackable1.QH868V5764
Unfortunately this always failed for my iOS 15.8.3 device (jailbroken). I couldn't find a DeveloperDiskImage for 15.8.3, but one for 15.7 but couldn't mount it. Were you testing this on macOS? I am using macOS sequoia 15.1.1 and Xcode 16.2

```
07:42:10 lockdown.c:278 lockdownd_stop_session(): success
07:42:10 idevice.c:1193 idevice_connection_disable_bypass_ssl(): Skipping bidirectional SSL shutdown. SSL error code: 5

07:42:10 idevice.c:1208 idevice_connection_disable_bypass_ssl(): SSL mode disabled
07:42:10 service.c:98 service_client_factory_start_service(): Could not start service com.apple.debugserver!
Could not start com.apple.debugserver!
Please make sure to mount the developer disk image first:
  1) Get the iOS version from `ideviceinfo -k ProductVersion`.
  2) Find the matching iPhoneOS DeveloperDiskImage.dmg files.
  3) Run `ideviceimagemounter` with the above path.
```

2025-01-04 21:07 UTC, TheDauntless commented on tools/ios/MASTG-TOOL-0118.md
> +    To sign an IPA file, you will need a valid iOS developer account, either free or paid. Both types come with certain restrictions, as explained on the Sideloadly website. We recommend creating a d
Oh, right. I've linked to the technique now which explains it. The paid account still has restrictions (365 days), so I think the text still makes sense.

2025-01-04 21:50 UTC, TheDauntless commented on techniques/ios/MASTG-TECH-0055.md
> +$ idevicedebug -d run sg.vp.UnCrackable1.QH868V5764
It works on my machine / device:

- macOS 15.2 (24C101)
- XCode 16.2 (16C5032a)
- iOS 15.8.3 (non-jb)
- idevicedebug 1.3.0-260-gc8cdf20

In installed via Sideloadly

```bash
idevicedebug -d run sg.vp.UnCrackable12          
working_directory: /private/var/mobile/Containers/Data/Application/9C89C011-33D7-421B-9934-B92488F49486

Setting logging bitmask...
Setting maximum packet size...
Setting working directory...
Setting argv...
app_argv[0] = /private/var/containers/Bundle/Application/F7FDC3A7-2055-46B8-A88B-2764BF84ACD2/UnCrackable Level 1.app/UnCrackable Level 1
Checking if launch succeeded...
Setting thread...
Continue running process...
```

2025-01-11 13:19 UTC, sushi2k requested changes
Done! 
Few small changes. But this is really a great update on how to do re-signing and run apps with Frida on iOS!

2025-01-11 13:19 UTC, sushi2k commented on techniques/ios/MASTG-TECH-0090.md
> +You can inject Frida into an application using @MASTG-TOOL-0039, @MASTG-TOOL-0118 or @MASTG-TOOL-0038
The ID MASTG-TOOL-0039 is correct for Frida, but we don't explain how to inject Frida into an app running on a non-jailbroken device. Shall we link to the Frida documentation instead?

```suggestion
You can inject Frida into an application using @MASTG-TOOL-0118 or @MASTG-TOOL-0038, or follow the [instructions from the Frida website](https://frida.re/docs/ios/#without-jailbreak).
```

2025-01-11 13:19 UTC, sushi2k commented on techniques/ios/MASTG-TECH-0090.md
> +wget https://github.com/frida/frida/releases/download/16.5.9/frida-gadget-16.5.9-ios-universal.dylib.gz
Let's tell them to always use the latest version. Today it's already 16.6.1.

```suggestion
$ wget https://github.com/frida/frida/releases/download/X.Y.Z/frida-gadget-X.Y.Z-ios-universal.dylib.gz
```

2025-01-11 13:19 UTC, sushi2k commented on techniques/ios/MASTG-TECH-0090.md
> +First, download the latest version of the Frida Gadget and move it to `/Users/<USER>/.cache/frida/gadget-ios.dylib`:
```suggestion
First, download the latest version of the Frida Gadget and move it to `/Users/<USER>/.cache/frida/gadget-ios.dylib`. Frida is released frequently, so find the latest version available on the [Github releases page](https://github.com/frida/frida/releases) or download on the command line:
```

2025-01-11 13:19 UTC, sushi2k commented on techniques/ios/MASTG-TECH-0090.md
> +gzip -d frida-gadget-16.5.9-ios-universal.dylib.gz
```suggestion
$ gzip -d frida-gadget-X.Y.Z-ios-universal.dylib.gz
```

2025-01-11 13:19 UTC, sushi2k commented on techniques/ios/MASTG-TECH-0090.md
> +mv frida-gadget-16.5.9-ios-universal.dylib /Users/MAS/.cache/frida/gadget-ios.dylib
```suggestion
mv frida-gadget-X.Y.Z-ios-universal.dylib /Users/MAS/.cache/frida/gadget-ios.dylib
```

2025-01-11 13:19 UTC, sushi2k commented on techniques/ios/MASTG-TECH-0092.md
> +After setting this set up, you only need to change the path in the `Fastfile` for the IPA you want to resign and execute the command again.
```suggestion
Once this is set up, all you need to do is change the path in the `Fastfile' for the IPA you want to resign and run the command again.
```

2025-01-11 13:19 UTC, sushi2k commented on tools/ios/MASTG-TOOL-0118.md
> +    To sign an IPA file, you will need a valid iOS developer account, either free or paid. Both types come with certain restrictions, as explained on the Sideloadly website. We recommend creating a d
Ok. But shall we remove this sentence? 

> "Both types come with certain restrictions, as explained on the Sideloadly website."

If this is explained on the sideloadly website, let's link to it. But I couldn't find it.

2025-01-20 07:09 UTC, TheDauntless commented on tools/ios/MASTG-TOOL-0118.md
> +    To sign an IPA file, you will need a valid iOS developer account, either free or paid. Both types come with certain restrictions, as explained on the Sideloadly website. We recommend creating a d
```suggestion
    To sign an IPA file, you will need a valid iOS developer account, either free or paid. Both types come with certain restrictions, as explained in @MASTG-TECH-0079. We recommend creating a dedicated developer account for signing test applications, and **not** using your personal Apple account.
```

2025-01-20 07:12 UTC, TheDauntless commented on techniques/ios/MASTG-TECH-0056.md
>  unzip Name.ipa
The goal is to not have the command prompts anymore so that it's easier to copy/paste: https://mas.owasp.org/contributing/5_Style_Guide/#8-code-and-shell-commands

2025-01-20 07:19 UTC, TheDauntless commented on techniques/ios/MASTG-TECH-0090.md
> +You can inject Frida into an application using @MASTG-TOOL-0039, @MASTG-TOOL-0118 or @MASTG-TOOL-0038
I've removed tool 39 and the link to the frida website. This technique is explaining how to do it on a non-jailbroken, so would be weird to link to the frida docs this way.

2025-01-20 07:19 UTC, TheDauntless commented on techniques/ios/MASTG-TECH-0090.md
> +You can inject Frida into an application using @MASTG-TOOL-0039, @MASTG-TOOL-0118 or @MASTG-TOOL-0038
```suggestion
You can inject Frida into an application using @MASTG-TOOL-0118 or @MASTG-TOOL-0038
```

2025-01-20 13:52 UTC, serek8 requested changes

2025-01-20 13:52 UTC, serek8 commented on techniques/ios/MASTG-TECH-0055.md
> +
@TheDauntless I see that iOS 17 requires you to attach a debugger first to use the Gadget properly, right? Maybe we could add a sentence or two at the beginning of this paragraph to give this background. Then maybe we could have a subsection about LLDB and then another one about attaching to a process with Frida gadget?

2025-01-20 13:52 UTC, serek8 commented on techniques/ios/MASTG-TECH-0090.md
> +After following any of the techniques of @MASTG-TECH-0057, your application will be running with the `get-task-allow` entitlement, which means it can be debugged. This means that the `frida` CLI tool
Are you sure it's a correct technique ID? It points to `Listing Installed Apps`

2025-01-20 14:18 UTC, TheDauntless commented on techniques/ios/MASTG-TECH-0055.md
> +
>I see that iOS 17 requires you to attach a debugger first to use the Gadget properly, right? 

Not entirely. If the app is running in debug mode, Frida can automatically inject into it and the app doesn't need to have the gadget included. However, if you did include the gadget yourself (e.g. Objection / Sideloadly), then the frida gadget library is loaded at startup, and then you do need to connect with lldb followed by Frida.

2025-01-20 15:57 UTC, serek8 commented on techniques/ios/MASTG-TECH-0055.md
> +
In this technique we include the gadget ourselves, so the LLDB will always be required, right? Would be nice to write a short context e.g.

```suggestion
On iOS 17, you need to launch an app with a debugger if you have repackaged it with a Frida gadget. The following steps show how to launch an app with a debugger

### Launching an app with LLDB debugger

```

I didn't test it myself but it looks like `iOS17 and newer` works for all iOS versions, no? In this case, maybe it's easier to skip the `iOS16 and older`? Or at least make it clear that `iOS17 and newer` is universal?

2025-01-20 16:23 UTC, cpholguera commented on techniques/ios/MASTG-TECH-0056.md
> +On a jailbroken device, you can circumvent this requirement using @MASTG-TOOL-0127, allowing you to install IPA files without obtaining a valid signature.
Add as a dedicated sub section.

This supposedly works via `appinst` however I could not get it to work after installing the .deb

2025-01-21 13:31 UTC, cpholguera commented on techniques/ios/MASTG-TECH-0056.md
> +On a jailbroken device, you can circumvent this requirement using @MASTG-TOOL-0127, allowing you to install IPA files without obtaining a valid signature.
```suggestion
**Disabling Signature Verification (optional)**: On a jailbroken device, you can bypass the signature verification requirement using @MASTG-TOOL-0127, which hooks the appropriate system daemon and disables signature verification for any installations you do with the tools below while it's enabled.
```

2025-01-21 13:40 UTC, cpholguera commented on techniques/ios/MASTG-TECH-0056.md
Could you please add `## Filza` and the tool page for it?

2025-01-29 07:17 UTC, sushi2k commented on techniques/ios/MASTG-TECH-0055.md
> +$ idevicedebug -d run sg.vp.UnCrackable1.QH868V5764
Somehow same issue for me. Not sure what I am doing wrong. As long as it worked for you let's keep as is.

2025-01-29 07:20 UTC, sushi2k approved these changes

2025-01-29 07:21 UTC, sushi2k reviewed
Comments from Jan and Carlos should be addressed before merging.

2025-02-08 04:34 UTC, sushi2k commented on tools/ios/MASTG-TOOL-0128.md
> +In addition to letting you browse the file system, you can also use Filza to easily install IPA files. Simply navigate to the IPA file on your filesystem, and click on `Install` in the top right corn
```suggestion
In addition to letting you browse the file system, you can also use Filza to easily install IPA files. Simply navigate to the IPA file on your filesystem, and click on `Install` in the top right corner.

```

2025-02-08 04:34 UTC, sushi2k commented on tools/ios/MASTG-TOOL-0128.md
> +In addition to letting you browse the file system, you can also use Filza to easily install IPA files. Simply navigate to the IPA file on your filesystem, and click on `Install` in the top right corn
Fix markdown error with newline

2025-02-08 04:34 UTC, sushi2k commented on techniques/ios/MASTG-TECH-0056.md
This was done @cpholguera

2025-02-09 13:24 UTC, cpholguera commented on techniques/ios/MASTG-TECH-0056.md
> +@MASTG-TOOL-0128 allows you to install an IPA file which is already located on your device. You can use either `scp` or airdrop to copy the IPA file to your device, after which you can simply navigat
```suggestion
@MASTG-TOOL-0128 allows you to install an IPA file which is already located on your device. You can use either `scp` or [AirDrop](https://support.apple.com/en-us/119857) to copy the IPA file to your device, after which you can simply navigate to the IPA file on your file system and click the `Install` button in the top right corner.
```

2025-02-09 13:32 UTC, cpholguera commented on techniques/ios/MASTG-TECH-0056.md
>  It is important to note that changing this value will break the original signature of the IPA file so you need to re-sign the IPA, after the update, in order to install it on a device on which the si
```suggestion
Note that changing this value will break the original signature, so you must re-sign the IPA (@MASTG-TECH-0092) to install it on a device that does not have signature validation disabled.
```

2025-02-09 13:33 UTC, cpholguera commented on techniques/ios/MASTG-TECH-0056.md
> +The IPA can also be directly installed on the iOS device via the command line with [ipainstaller](https://github.com/autopear/ipainstaller "IPA Installer"). Naturally, this requires a jailbroken devi
```suggestion
The IPA can also be directly installed on the iOS device via the command line with [ipainstaller](https://github.com/autopear/ipainstaller "IPA Installer"). Naturally, this requires a jailbroken device, as otherwise you cannot SSH into the device. After copying the file over to the device, for example via scp or [AirDrop](https://support.apple.com/en-us/119857), you can execute `ipainstaller` with the IPA's filename:
```

2025-02-09 13:42 UTC, cpholguera commented on techniques/ios/MASTG-TECH-0055.md
> +Finally, you can attach `lldb` using the following commands:
```suggestion
Finally, you can attach @MASTG-TOOL-0057 using the following commands:
```

2025-02-09 13:47 UTC, cpholguera requested changes

2025-02-09 13:47 UTC, cpholguera commented on techniques/ios/MASTG-TECH-0055.md
> +In a new terminal window, connect to the Frida gadget, just like in the iOS17 scenario:
```suggestion
In a new terminal window, connect to the Frida gadget, just like in the iOS 17 scenario:
```

2025-02-09 13:47 UTC, cpholguera commented on techniques/ios/MASTG-TECH-0055.md
> +## iOS16 and older
```suggestion
## iOS 16 and older
```

2025-02-09 13:47 UTC, cpholguera commented on techniques/ios/MASTG-TECH-0055.md
> +## iOS17 and newer
```suggestion
## iOS 17 and newer
```

2025-02-11 16:49 UTC, cpholguera approved these changes
Amazing improvements Jeroen, thank you so much!

2025-02-11 16:58 UTC, merged